V.1.23
pentacode/site pull request #30
Opened 2022-09-03 18:50 UTC by J0hhny

Erste Version, muss ich selbst noch korrigieren - mache ich noch diesen Abend oder morgen früh.

2022-09-03 23:30 UTC, J0hhny commented
Sollte jetzt soweit fertig sein - hoffe das passt vom allgemeinen Stil und Inhalt.

2022-09-04 09:14 UTC, MaKleSoft commented on news/update_v1.23/index.md
> +title: "Pentacode v1.22: Integrierte Formulare und Sofortmeldungen bei der Rentenversicherung"
```suggestion
title: "Pentacode v1.23: Integrierte Formulare und Sofortmeldungen bei der Rentenversicherung"
```

2022-09-04 09:17 UTC, MaKleSoft commented on news/update_v1.23/index.md
> +Besonders im Gastrogewerbe ist das stetiges Kommen und Gehen vieler Mitarbeiter
Am besten nicht mehr so viel auf Gastro beziehen sondern allgemeiner halten.

2022-09-04 09:33 UTC, MaKleSoft commented on news/update_v1.23/index.md
> +<img src="angeben_übernehmen.png"/>
```suggestion
<img src="angaben_übernehmen.png"/>
```

2022-09-04 09:33 UTC, MaKleSoft commented on news/update_v1.23/index.md
> + und ihre frei gewordene sinnvoller nutzen - zum Beispiel indem Sie die letzten
```suggestion
 und ihre frei gewordene Zeit sinnvoller nutzen - zum Beispiel indem Sie die letzten
```

2022-09-04 09:42 UTC, MaKleSoft requested changes
Schreibstil und Inhalt gefällt mir sehr gut! Vom Ablauf her kommt aber normalerweise immer erst die Sofortmeldung und dann der Personalfragebogen, deshalb wäre es gut, wenn der Artikel auch so strukturiert wäre. Vielleicht kommst du noch dazu, das auszubessern - ist jetzt aber kein Dealbreaker.

Es fehlt allerdings noch das Titelbild und das GIF ist nicht gut geframed (links abgeschnitten und rechts unnötiger Whitespace. Das bitte noch ausbessern.

2022-09-04 13:47 UTC, MaKleSoft approved these changes

2022-09-04 13:47 UTC, merged