Aktualisierung einstellung arbeitsbereiche
pentacode/site pull request #37
Opened 2022-09-09 18:20 UTC by J0hhny

Kleine Überarbeitung wegen den Feiertagen unter Arbeitsbereiche.
Einzige Unklarheit:
Für was werden die Adressdaten alles benötigt? Das konnte ich nicht spezifizieren, weil wenn diese zusätzlich für Dokumente genutzt werden würde ich hier einen Vermerk setzten, dass diese aufjedenfall wahrheitstreu eingetragen werden.

**Deshalb noch nicht mergebereit!**

2022-09-13 06:13 UTC, MaKleSoft requested changes

2022-09-13 06:13 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/arbeitsbereiche/index.md
> +Sie können weitere Standorte anlegen, indem Sie auf "+ Neuer Standort" klicken.
```suggestion
Sie können weitere Standorte anlegen, indem Sie auf {% button icon="plus", label="Neuer Standort" %} klicken.
```

2022-09-13 06:13 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/arbeitsbereiche/index.md
> +Sie dazu einfach den gewünschten Feiertag an.
Bitte für das anpassen von Feiertagen einen extra Abschnitt anlegen, so dass es auch über die Suche gefunden werden kann.

2022-09-13 06:13 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/arbeitsbereiche/index.md
> +und ???
Zu der Verwendung brauchst du hier nichts schreiben. Die Adresse wird aktuell auch nicht wirklich verwendet.

2022-09-16 07:10 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/arbeitsbereiche/index.md
> +Sie dazu einfach den gewünschten Feiertag an.
@J0hhny Machst du das noch, bitte? Wenn erledigt bitte wieder Review anfordern.

2022-09-21 12:10 UTC, J0hhny commented
Jetzt sind die Feiertage ein separater Überpunkt

2022-09-22 13:37 UTC, MaKleSoft requested changes

2022-09-22 13:37 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/arbeitsbereiche/index.md
> +{% figure caption="Ein neuer Standort soll zwei zusätzliche Feiertage anerkennen. %}
```suggestion
{% figure caption="Ein neuer Standort soll zwei zusätzliche Feiertage anerkennen." %}
```

2022-09-22 13:37 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/arbeitsbereiche/index.md
> +<img src = "neuer-standort.png"/>
```suggestion
<img src="neuer-standort.png"/>
```

2022-09-22 13:45 UTC, MaKleSoft approved these changes

2022-09-22 13:45 UTC, merged