Dokumentenarchiv 2.0
pentacode/site pull request #4
Opened 2022-05-26 18:19 UTC by J0hhny

Komplett neue Branche erstellt - hoffe das ist richtig so

Die überarbeitete Version (fast komplett neu), hoffe das passt so strukturell besser.
Habe leider Probleme die fontawesome-icons darzustellen - bei mir wird nahezu überall das Platzhalter icon angezeigt. Bisher konnte ich dieses Problem leider nicht lösen - es könnte also sein, dass noch Schreibfehler in den "icon-codes" sind. 

Zusätzlich hatte ich Probleme einen Screenshot der Dokumente in der Mitarbeiterapp zu machen, da ich mich zwar einladen konnte - dann aber immer Probleme mit der Demo-Version der Mitarbeiterapp hatte (siehe Screenshot). Denke die Beschreibung dieser Funktion sollte dann aber auch eher in die Rubrik "Mitarbeiterapp" fallen, welche ja auch generell noch nicht ganz ausgearbeitet ist (bisher nur Beschreibung der Installation). 

Sonst noch einen schönen Feiertag!

![perso demo pentacode app_home_next= date=2022-05-26(iPad Air)](https://user-images.githubusercontent.com/104359585/170550508-66c26729-fb81-439e-b5cf-403e0dfa454a.png)

2022-05-30 14:53 UTC, MaKleSoft commented on content/hilfe/Handbuch/Einstellungen/dokumente/index.md
> +Auch können Sie schon bestehende Kategorien einfach bearbeiten. Sollten Sie den **Namen** ändern wollen drücken Sie auf den aktuellen Namen der Kategorien. Löschen den bisherigen Namen und geben den
Diesen Artikeln bitte auch noch wrappen.

2022-05-31 09:21 UTC, MaKleSoft requested changes
Hatte jetzt doch noch einige Verbesserungsvorschläge 😄 Aber alles in allem schon recht gut!

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/Einstellungen/dokumente/index.md
> +Hier können Sie die farbliche Codierung ihrer **Dokumentenkategorien**
```suggestion
Hier können Sie die Namen und farbliche Codierung ihrer **Dokumentenkategorien**
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/Einstellungen/dokumente/index.md
> +{{<icon = "tag">}}-**icon** und gaben den gewünschten Namen ein. Zusätzlich
```suggestion
{{<icon "tag" >}}-**icon** und geben den gewünschten Namen ein. Zusätzlich
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/Einstellungen/dokumente/index.md
> +nachdem Sie auf **mehr** gedrückt haben.
Ich verstehe, dass du versuchst, abwechslungsreich zu formulieren, aber ein "eleganter" Satzbau ist leider immer etwas schwieriger zu verstehen. Beim Beschreiben von Vorgängen sind kurze Schritt-für-Schritt Anweisungen in Listenform deutlich einfacher zu verdauen. Das ganze muss nicht unbedingt schön formuliert sein, solange es einfach zu verstehen ist. Brauchst dich als nicht verkünsteln 😉. Vorschlag:

```suggestion
So legen Sie eine neue Kategorie an:

1. Klicken Sie auf den Button {{<button icon="plus" label="Neue Kategorie" >}}
2. Es erscheint ein Textfeld - geben Sie hier den gewünschten **Kategorienamen** ein.
3. Wählen Sie die gewünschte Darstellungsfarbe, indem Sie auf das farbige Kästchen neben dem Eingabefeld klicken.
4. Klicken Sie den {{<button label="Speichern" >}}-Button.
```

(Auf manche Details musst du nicht unbedingt eingehen. Z.B. das Auswählen von "mehr..." Farben könnte man in diesem Fall aussparen da nicht essentiell. Oder du schreibst es in eine eigene Box als "Tipp".)

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/Einstellungen/dokumente/index.md
> +die Änderungen verworfen.
Siehe obiger Kommentar. Auch hier wären Stichpunkte besser.

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/Einstellungen/dokumente/index.md
> +einfacher.
Genau so stell ich mir eine gute Einleitung vor 👍

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +haben**. So bietet es sich an, Lebensläufe, Arbeitszeugnisse, Bescheinigungen
Der erste Satz hört sich ein bisschen komisch an finde ich. Findest du da noch ne schönere Formulierung? Ansonsten gute Einleitung!

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +Dokumentenkategorien filtern.
👍

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +Mitarbeiter einsehen.">}} <img src = "dokumentenübersicht.png" /> {{</figure>}}
Sorry, dass hätte ich vielleicht dazu sagen sollen: Bei Elementen mit besonderer Syntax musst du mit den Zeilenumbrüchen ein bisschen aufpassen. Ein Zeilenumbruch innerhalb der Anführungszeichen führt hier zum Beispiel zu einem Syntaxfehler. Generell bitte immer erst testen, ob die Seite kompiliert bevor du Änderungen pushst.

```suggestion
{{<figure caption="Hier können Sie die gespeicherten Datein all ihrer Mitarbeiter einsehen.">}}
<img src="dokumentenübersicht.png" />
{{</figure>}}
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +explizite Dokumente zu suchen oder auch neue Dateien hinzufügen. Von hier aus
```suggestion
, die Dokumente eines bestimmten Mitarbeiters einzusehen,
Einträge gezielt zu suchen oder auch neue Dateien hinzufügen. Von hier aus
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +{{<figure caption = "">}} <img src = "einzelansicht.png" > {{</figure>}}
```suggestion
{{<figure caption="">}} <img src = "einzelansicht.png" > {{</figure>}}
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +> Tipp {{<icon = "bulb">}} Haben Sie eine Datei gerade erst von ihrem
```suggestion
> Tipp {{<icon "lightbulb" >}} Haben Sie eine Datei gerade erst von ihrem
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +Dokumenteneigenschaften festlegen können.
Auch hier bitte lieber Schritt-für-Schritt in Listenform. Drag & Drop würde ich vielleicht als "Tipp" in eine eigene Box packen - oder du machst eine eigene Unterüberschrift. Für die Beschreibung der Felder kannst du einfach auf "Dokumenteneigenschaften" verlinken.

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +{{</figure>}}
Das darf ruhig seine eigene Überschrift kriegen und sollte am Anfang des Artikels (direkt nach "Einzelansicht") stehen. Und es darf deutlich ausführlicher sein:

```suggestion

## Dokumenteneigenschaften

Jedes Dokument enthält folgende Felder und Eigenschaften:

### Name

Die Bezeichnung des Dokuments. Diese dient für Darstellungszwecke und erleichtert
außerdem die Suche nach bestimmten Dokumenten.

### Mitarbeiter

Jedes Dokument ist einem bestimmten Mitarbeiter zugeordnet. Diese Zuordnung
kann jederzeit durch einen Klick auf das Feld **Mitarbeiter** geändert werden.

### Datei

Jedem Dokument kann eine beliebige Datei **bis zu einer Größe von 5MB** angehängt werden. Unterstütze Formate
sind **PDFs**, **Bilder (JPEG und PNG)**, **Word- und Excel-Dateien** sowie einfache **Text-Dateien**.

### Datum

Das **Datums-Feld** ist für die chronologische Einordnung des Dokumentes vorgesehen.
Wenn Sie eine Datei auswählen, wird hier automatisch der Zeitpunkt der letzten
Bearbeitung eingetragen - sie können aber auch ein beliebiges anderes Datum wählen.
Generell sollte das Datumsfeld des Dokumentes das Entstehungsdatum der angehängten
Datei widerspiegeln.

### Kommentar

Im Textfeld **Kommentar** kann, wie der Name schon sagt, dem Dokument ein
Kommentar mit zusätzlichen Informationen hinzugefügt werden.

### Kategorien

Besonders relevant ist das Feld **Kategorien**, hier können dem Dokument eine oder
mehrere Kategorien zugeordnet werden, welche es später einfacher machen nach
diesem Dokument zu **filtern** und es schnell zu finden. Tippen Sie dazu einfach
den Namen der gewünschten Kategorie in das Textfeld, bis diese auftaucht. Wenn
Sie eine neue **Kategorie erstellen** und das Dokument dieser zuordnen wollen,
geben Sie den Namen der neuen Kategorie ein und drücken Sie auf den
{{<icon "tag" >}}-**Button** mit dem Namen der Kategorie daneben. Jetzt ist das
Dokument den ausgewählten Kategorien zugeordnet und es ist einfach danach zu
[filtern](#kategorienfilter).

{{<figure caption = "Der Name der Datei sowie das aktuelle Datum werden im Normalfall vom PC übernommen.">}}
<img src = "eingabefenster.png" />
{{</figure>}}
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +## Dokumente abrufen
```suggestion
## Dokument öffnen
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +>Tipp {{<icon="bulb">}} Mit {{<key "strg">}} + {{<key "+">}} und {{<key
```suggestion
>Tipp {{<icon "lightbulb" >}} Mit {{<key "strg">}} + {{<key "+">}} und {{<key
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +Sie das gesuchte Dokument unter Tausend finden können. Pentacode bietet Ihnen
```suggestion
Sie das gesuchte Dokument selbst unter einer Vielzahl von anderen Dokumenten finden können. Pentacode bietet Ihnen
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +"filter">}}-**Button** im rechten oberen Eck aus. Nun können Sie durch Ab- und
Du hast es wahrscheinlich schon gemerkt, aber die Syntax für icons ist wie folgt:
```
{{<icon "[icon_name]" >}}
```
**Nicht**
```
{{< icon = "[icon_name]" >}}
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +Wählen Sie dazu die mit den {{<icon="tag">}} markierten Kategorien am oberen
```suggestion
Wählen Sie dazu die mit den {{<icon "tag" >}} markierten Kategorien am oberen
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +allen Dokumenten zurückzukehren drücken Sie auf den {{<icon="tags">}}
```suggestion
allen Dokumenten zurückzukehren drücken Sie auf den {{<icon "tags" >}}
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +"beispielfilter.png" /> {{</figure>}}
```suggestion
{{<figure caption="Hier wurden die Mitarbeiter nach der Abteilung Küche und die Dokumentenkategorie nach ´Hygieneschulung´ gefiltert">}}
<img src="beispielfilter.png" />
{{</figure>}}
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +[speichern](#dokumente-sichern) und lokal auf ihrem PC bearbeiten.
```suggestion
So **bearbeiten** Sie eine Datei:

1. [Öffnen](#dokument-öffnen) Sie das Dokument
2. Drücken Sie nun auf den {{<icon "pencil-alt">}}-**Button** im
rechten oberen Eck, um wieder in das [Dialogfeld](#dokumenteneigenschaften) zu
gelangen, in dem Sie Namen, Kategorien und Kommentar des Dokuments bearbeiten
können.
3. Klicken Sie auf {{< button label="Speichern" >}}

> Innerhalb von Pentacode können Sie den Inhalt (z.B den Text in einem
Word-Dokument) einer Datei nicht ändern, dazu müssen Sie das Dokument
[speichern](#dokumente-sichern) und lokal auf ihrem PC bearbeiten.
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +Wenn Sie eine Kopie eines Dokuments auf ihrem Gerät **speichern** wollen, öffnen
```suggestion
Wenn Sie eine Kopie eines Dokuments auf ihrem Gerät **speichern** wollen, [öffnen](#dokument-öffnen)
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +Wenn Sie eine Kopie eines Dokuments auf ihrem Gerät **speichern** wollen, öffnen
Der Punkt ist kurz genug, dass ein Absatz reicht. Auch hier könnte man aber eine Schritt-für-Schritt Liste draus machen.

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +öffnen">}} <img src = "bearbeiten.png"/> {{</figure>}}
```suggestion
{{<figure caption="Bewegen Sie in der Einzelansicht ihren Cursor über ein Dokument, erscheinen die Buttons zum Bearbeiten auch ohne das Dokument zu öffnen">}}
<img src = "bearbeiten.png"/>
{{</figure>}}
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +## Dokumentenzugriff
```suggestion
## Berechtigungen erteilen
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +## Dokumentenzugriff
Ich würde vielleicht sogar direkt in der Einleitung erwähnen, dass bestimmte Berechtigungen benötigt werden, mit Verlinkung auf diesen Bereich.

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +[hier](/hilfe/handbuch/einstellungen/dokumente) für mehr Informationen.
Bonuspunkte für die Verlinkung auf den anderen Artikel 👍

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +>**Tipp** {{<icon="bulb">}} Über das Dokumentenarchiv können Sie
```suggestion
>**Tipp** {{<icon "lightbulb" >}} Über das Dokumentenarchiv können Sie
```

2022-05-31 09:21 UTC, MaKleSoft commented on content/hilfe/Handbuch/mitarbeiter/dokumente/index.md
> +"dokumentenberechtigung.png" /> {{</figure>}}
```suggestion
{{<figure caption="Erteilen Sie einem Manager die Berechtigung **Mitarbeiter** kann er automatisch auch das Dokumentenarchiv bearbeiten">}}
<img src="dokumentenberechtigung.png" />
{{</figure>}}
```

2022-06-03 11:01 UTC, J0hhny reviewed
Soweit fertig, hoffe alles passt soweit. 
Ich fand die Rangreihe von "Dokumenteneigenschaften" aber eigentlich passend, da dieses Dialogfeld beim öffnen von Dokumenten noch nicht erscheint und erst beim hinzufügen/bearbeiten relevant wird. Zumindest logisch passt es so eigentlich besser hinter "Dokumente hinzufügen" als "Einzelansicht"

2022-06-04 07:35 UTC, merged