Umsätze Aktualisierung
pentacode/site pull request #40
Opened 2022-09-15 14:56 UTC by J0hhny

Aktualisierte Version der Umsätze - teilweise neue Screenshots, Beschreibung der Debitorenfunktion, kleine Verbesserungen etc.
Ich habe den Punkt "Statistische Erfassung" (mittels Umsatzgruppen) zu Umsatzgruppen gepackt, da es thematisch besser passt.

2022-09-15 14:59 UTC, J0hhny commented on hilfe/handbuch/umsaetze/tagesabrechnung/index.md
>  {% figure caption="Ignorieren Sie für die statistische Erfassung die buchhalterischen Angaben, wählen Sie jedoch den zutreffenden UST-Satz" %}
Hier bin ich mir nicht sicher ob dieser Teil auch in der Tagesabrechnung bestehen soll - der gleiche Inhalt steht schon unter Umsatzgruppen.

2022-09-15 15:00 UTC, J0hhny commented on hilfe/handbuch/umsaetze/tagesabrechnung/index.md
>  {% figure caption="Ignorieren Sie für die statistische Erfassung die buchhalterischen Angaben, wählen Sie jedoch den zutreffenden UST-Satz" %}
Also fast alles unter "Statistische Erfassung"

2022-09-16 07:43 UTC, MaKleSoft requested changes
Siehe Kommentare.

2022-09-16 07:43 UTC, MaKleSoft commented on hilfe/handbuch/umsaetze/Debitoren/index.md
> +Schuldner steht.
```suggestion
Besonders bei großen Aufträgen ist eine Bestellung auf Rechnung in vielen Betrieben nicht unüblich.
Unter dem Reiter **Debitoren** finden Sie eine Auflistung aller auf
Rechnung erbrachten Leistungen und können so stets nachvollziehen, wie es um ihre
Schuldner steht. 
```
Finde es nett, dass du die Einleitung auch immer etwas ausschmückst, aber in diesem Fall wirkt das ganze ein bisschen gezwungen und liest sich auch nicht so schön. Glaube, du kannst das noch besser - aber du musst das auch nicht unbedingt für jeden Artikel machen. Also gerne auch etwas kürzer / sachlicher fassen wenn dir grade nichts Gutes einfällt.

2022-09-16 07:43 UTC, MaKleSoft commented on hilfe/handbuch/umsaetze/Debitoren/index.md
> +Schuldversprechen. Hier sind alle Daten mit angegeben, welche in der
"Schuldversprechen" klingt finde ich ein bisschen komisch... Schreib einfach "Rechnungen"...

2022-09-16 07:43 UTC, MaKleSoft commented on hilfe/handbuch/umsaetze/Debitoren/index.md
> +Sie können die Liste der Debitoren auf mehrere Weisen filtern:
```suggestion
Sie können die Liste der Debitoren auf verschiedene Weise filtern:
```

2022-09-16 07:43 UTC, MaKleSoft commented on hilfe/handbuch/umsaetze/Debitoren/index.md
> +-  **Zeitpunkt des Schuldversprechens** - Sie können nach spezifischen Jahren oder
```suggestion
-  **Rechnungsdatum** - Sie können nach spezifischen Jahren oder
```
Bitte keine umständlichen Umschreibungen wenn es auch ein einfaches Wort dafür gibt 😉

2022-09-16 07:43 UTC, MaKleSoft commented on hilfe/handbuch/umsaetze/Debitoren/index.md
> +   einsehen, klicken Sie auf den Regler **bezahlt** in der oberen rechten Ecke
```suggestion
   einsehen, klicken Sie auf den Regler {% button icon="toggle-on", label="bezahlt" %} in der oberen rechten Ecke
```

2022-09-16 07:43 UTC, MaKleSoft commented on hilfe/handbuch/umsaetze/Debitoren/index.md
> +<img src="debitoren-filter.gif"/>
Bitte bei den GIFs noch ein bisschen mehr darauf achten, dass nichts abgeschnitten ist (damit meine ich auch das "padding" drumherum, also ein immer ein bisschen Abstand zu den UI-element wahren). Außerdem wäre es gut, wenn das Seitenverhältnis ein bisschen weniger extrem wäre, also eher 3:2 als 2:1.

2022-09-16 07:43 UTC, MaKleSoft commented on hilfe/handbuch/umsaetze/Debitoren/index.md
> +Sobald ein Debitor eine Rechnung beglichen hat, markieren Sie diese als gezahlt.
```suggestion
Sobald ein Debitor eine Rechnung beglichen hat, markieren Sie diese als bezahlt.
```

2022-09-16 07:43 UTC, MaKleSoft commented on hilfe/handbuch/umsaetze/erloeszuordnung.md
> +<img src="erlöszuordnung.gif"/>
Auch hier wieder vor allem links zu wenig Abstand zum Rand und Seitenverhältnis ein bisschen zu breit. Ist nur ein Detail aber wir sind schließlich Perfektionisten 😉

2022-09-16 07:43 UTC, MaKleSoft commented on hilfe/handbuch/umsaetze/tagesabrechnung/index.md
>  {% figure caption="Ignorieren Sie für die statistische Erfassung die buchhalterischen Angaben, wählen Sie jedoch den zutreffenden UST-Satz" %}
Japp, hast Recht. Ein Verweis auf den entprechenden Bereich sollte ausreichen.

2022-09-21 16:14 UTC, J0hhny commented
Soweit alle Verbesserungen integriert - einzig eine Sache ist mir aufgefallen:
Beim Gif der Debitoren-Filter sieht man einige Rechnungen des Kunden und diese scheinen nicht anonymisiert zu sein - kann man das so auf der Seite zeigen? Natürlich weiß keiner wer der Kunde ist und mit den Debitoren ist nicht viel anzufangen aber der Kunde selbst kann das ja gut erkennen, dass seine Daten hier nur halb-anonymisiert verwendet wurden.
Deine Meinung dazu @MaKleSoft ?

2022-09-22 13:49 UTC, MaKleSoft approved these changes
Passt :)

2022-09-22 13:55 UTC, merged