Industrieminuten
pentacode/site pull request #55
Opened 2022-10-04 11:37 UTC by J0hhny

Tipps und Tricks Artikel zu Industriezeit
Erstmal nur generelle Beschreibung und Umrechnung

-> Hatte Probleme, dass die Abschnitte alle zentriert waren deswegen der *align über html code*, weiß aber nicht ob das Probleme mit dem Layout von Njk macht
-> Die Überschriften sind Blau statt schwarz in normalen Artikeln - konnte aber bis jetzt nicht herausfinden woran das lag

2022-10-04 11:41 UTC, MaKleSoft commented on hilfe/tips_und_rezepte/industrieminuten/index.md
> +layout: layouts/hilfe/index.njk
Hier liegt das Problem. Das layout sollte `layouts/hilfe/single.njk` sein.

2022-10-04 11:42 UTC, MaKleSoft commented on hilfe/tips_und_rezepte/industrieminuten/index.md
> +<div align="left">
Bitte wieder entfernen.

2022-10-04 11:42 UTC, MaKleSoft commented on hilfe/tips_und_rezepte/industrieminuten/index.md
> +</body>
Bitte wieder entfernen

2022-10-05 08:35 UTC, J0hhny commented
Erledigt

2022-10-05 11:13 UTC, MaKleSoft requested changes
Sieht gut aus! Hatte noch ein paar Verbesserungen aber sonst sehr gute Arbeit.

2022-10-05 11:13 UTC, MaKleSoft commented on hilfe/tips_und_rezepte/industrieminuten/index.md
> +Um zu verstehen wie Pentacode Arbeitszeiten berechnet und darstellt ist es
```suggestion
Um zu verstehen wie Pentacode Arbeitszeiten und andere Stundenwerte berechnet und darstellt ist es
```

2022-10-05 11:13 UTC, MaKleSoft commented on hilfe/tips_und_rezepte/industrieminuten/index.md
> +darzustellen. **Eine Industrieminute ist dabei 1/100 Stunde - also 36
```suggestion
darzustellen. **Eine Industrieminute ist dabei 1/100 Stunde - also 0,6 Minuten oder 36
```

2022-10-05 11:13 UTC, MaKleSoft commented on hilfe/tips_und_rezepte/industrieminuten/index.md
> +Sekunden.** In Dezimal dargestellt ist eine Industrieminute also 0,01 Stunden.
```suggestion
Sekunden.** In Dezimaldarstellung entspricht eine Minute also 0,01 Stunden. Eine "Echtminute" hingegen entspricht 1/60 Stunde oder ~ 0,017 Stunden.
```

2022-10-05 11:13 UTC, MaKleSoft commented on hilfe/tips_und_rezepte/industrieminuten/index.md
> +Urlaubstage, Personalkosten etc. in Dezimal problemlos funktionieren.
```suggestion
Urlaubstage, Personalkosten etc. im Dezimalsystem problemlos funktionieren.
```

2022-10-05 11:13 UTC, MaKleSoft commented on hilfe/tips_und_rezepte/industrieminuten/index.md
> +Echtminuten zu Industrieminuten: EM/60 x 100 <br>
```suggestion
Echtminuten zu Industrieminuten:
$$ IM = {EM \over 60} * 100 $$
```

2022-10-05 11:13 UTC, MaKleSoft commented on hilfe/tips_und_rezepte/industrieminuten/index.md
> +Industrieminuten zu Echtminuten: IM/100 x 60
```suggestion
Industrieminuten zu Echtminuten:
$$ EM = IM \over 100 * 60 $$
```

2022-10-14 12:25 UTC, J0hhny commented
- $$ IM = {EM \over 60} * 100 $$ - 
Sollte das LaTeX Code sein? Die Darstellung auf der Webseite funktioniert leider nicht - müsste man dafür nicht ein spezielles Paket laden?

2022-10-14 12:25 UTC, J0hhny commented
Deswegen auch noch kein Update vom Branch

2022-10-14 12:35 UTC, MaKleSoft commented
> Sollte das LaTeX Code sein? 

Japp, genau. Hm, schade ich dachte das wäre unterstützt. Gut dann schreibste einfach

    `IM = EM / 60 * 100`

2022-10-21 14:10 UTC, J0hhny commented
Paar kleine Verbesserungen - sollte mergebereit sein

2022-10-24 14:09 UTC, merged