Steuerdaten minijobber
pentacode/site pull request #60
Opened 2022-10-22 14:24 UTC by J0hhny

Noch nicht mergebereit

Unklarheiten:
- Ist die Datierung vom Datum so gut? (also zum "stichtag" ) oder soll das eher noch davor sein
- Wird die Steuernummer wirklich mit der Sofortmeldefunktion weitergeleitet? Macht ja eigentlich nur Sinn und so bin ich mal davon ausgegangen, da ich aber grad nicht in die Demoumgebung komm konnte ich das nicht überprüfen

-> Ich denke gerade darüber nach wie viel Sinn ein Tips&Tricks Artikel zur gemeinsamen Verwendung von Sofortmeldung und Personalfragebogen und deren Vorteilen macht - die Funktion selbst wurde ja schon im Handbuch beschrieben aber etwas zur gemeinsamen Nutzung und Optimierung dieser Funktion

2022-10-27 14:10 UTC, MaKleSoft requested changes
> Ist die Datierung vom Datum so gut? (also zum "stichtag" ) oder soll das eher noch davor sein

Davor - am besten ein paar Tage nach Bekanntwerdung.

> Wird die Steuernummer wirklich mit der Sofortmeldefunktion weitergeleitet? Macht ja eigentlich nur Sinn und so bin ich mal davon ausgegangen, da ich aber grad nicht in die Demoumgebung komm konnte ich das nicht überprüfen

Japp, wird sie, ist aber nur notwendig falls die Sozialversichungerungsnummer nicht vorliegt.
Passt aber schon so wie du das geschrieben hast.

2022-10-27 14:10 UTC, MaKleSoft commented on blog/update_v1.23/index.md
> +layout: layouts/news/single.njk
Das bitte weglassen

```suggestion
```

2022-10-27 14:10 UTC, MaKleSoft commented on blog/steuerdaten_minijobber/index.md
> +--> Steuer ID in Sofortmeldung
Ist das ein Platzhalter?

2022-10-27 14:10 UTC, MaKleSoft commented on blog/steuerdaten_minijobber/index.md
> +cover: "steuerunterlagen.webp"
Super Bildwahl 👍

2022-10-27 14:10 UTC, MaKleSoft commented on blog/steuerdaten_minijobber/index.md
> +Lohnsteuerabgaben müssen aber auch sie entrichten. Diese werden gemeinsam mit
```suggestion
Minijobber unter der 520€ Grenze sind zwar einkommenssteuerbefreit,
ein Arbeitgeberanteil der Lohnsteuerabgaben muss aber trotzdem entrichtet werden. Dieser wird gemeinsam mit
```

2022-10-27 14:10 UTC, MaKleSoft commented on blog/steuerdaten_minijobber/index.md
> +"*Datenbaustein Steuerdaten (DBST)*" nennt der Gesetzgeber den Satz an Informationen
```suggestion
"Datenbaustein Steuerdaten (DBST)" nennt der Gesetzgeber den Satz an Informationen
```

2022-10-27 14:10 UTC, MaKleSoft commented on blog/steuerdaten_minijobber/index.md
> +auch noch an die Minijobzentrale melden müssen.<br>
```suggestion
auch noch an die Minijobzentrale melden müssen.
```

2022-10-27 14:10 UTC, MaKleSoft commented on blog/steuerdaten_minijobber/index.md
> +Zum Glück nimmt **Pentacode mit seiner Personalfragebogen und
```suggestion
Zum Glück nimmt **Pentacode mit seiner Personalfragebogen- und
```
Hier könntest du eigentlich auch schon verlinken.

2022-10-27 14:10 UTC, MaKleSoft commented on blog/steuerdaten_minijobber/index.md
> +und übermittelt diese an die Minijobzentrale. <br>
```suggestion
und übermittelt diese an die Minijobzentrale.
```

2022-10-27 14:12 UTC, MaKleSoft commented
Guter Artikel! Bitte noch die paar Änderungen umsetzen dann sollte es bereit zum mergen sein.

2022-10-31 18:21 UTC, J0hhny commented
Punkte überarbeitet - konnte nicht ganz rausfinden wo mein Bild für die Artikel gespeichert ist / Wie ich darauf verweisen kann.
Das wär das einzige was noch fehlt.

2022-11-03 10:12 UTC, MaKleSoft commented
> konnte nicht ganz rausfinden wo mein Bild für die Artikel gespeichert ist / Wie ich darauf verweisen kann.

Das `author: jseidel` oben in der Datei reicht aus. Die entsprechenden Daten waren in diesem Branch einfach noch nicht hinterlegt.

2022-11-03 10:13 UTC, MaKleSoft approved these changes

2022-11-03 10:13 UTC, merged