Midijobs
pentacode/site pull request #67
Opened 2022-12-02 12:37 UTC by J0hhny

Artikel zum Midijobverhältnis - relativ selbsterklärend.

Einziges Problem:
Ich wollte zur Anmeldung des Midijobbers auf unsere **Sofortmeldungsfunktion** verweisen - bin mir aber nicht 100% sicher ob wir **auch bei der Krankenkasse melden oder nur bei der Rentenversicherung bzw. ob diese das dann weiterleitet an die KK.** Hab auf die Schnelle nichts beim suchen gefunden und vielleicht weißt du das ja gleich.

Deshalb letzter Teil noch nicht fertig

2022-12-05 15:06 UTC, MaKleSoft requested changes
Sehr schön! Gut recherchiert und schön geschrieben. Bitte noch ein bisschen besser auf Rechtschreibung achten (Spellcheck aktiviert?). Was das Thema Meldung angeht kenn ich mich auch nicht aus. Vielleicht kann @Lorenz147 das weiterhelfen, ansonsten kannst du das Thema von mir aus auch einfach unterschlagen - der Artikel hat so schon genug Substanz meine ich.

2022-12-05 15:06 UTC, MaKleSoft commented on blog/midijob/index.md
> +Spanne **zwischen 520€ - 1.600€ Sozialversicherungsbeiträge langsam angehoben**, um
```suggestion
Spanne **zwischen 520 € - 1.600 € Sozialversicherungsbeiträge langsam angehoben**, um
```
Bitte immer ein Leerzeichen zwischen Betrag und Euro-Zeichen.

2022-12-05 15:06 UTC, MaKleSoft commented on blog/midijob/index.md
> +vollständig versicht und hat Anrecht auf alle Sozialansprüche, welche der
```suggestion
vollständig versichert und hat Anrecht auf alle Sozialansprüche, welche der
```

2022-12-05 15:06 UTC, MaKleSoft commented on blog/midijob/index.md
> +Bereich der Gleitzone. Die Lohnsteuer hingegen ist zustäzlich abhängig von der Steuerklasse, im unteren Bereich der Gleitzone haben die meißten Arbeitnehmer dadurch
```suggestion
Bereich der Gleitzone. Die Lohnsteuer hingegen ist zusätzlich abhängig von der Steuerklasse, im unteren Bereich der Gleitzone haben die meisten Arbeitnehmer dadurch
```

2022-12-05 15:06 UTC, MaKleSoft commented on blog/midijob/index.md
> +aufgeteilt wird, sinkt der Anteil der Sozialabgaben von den ursprünglichen 28% für
```suggestion
aufgeteilt wird, sinkt der Anteil der Sozialabgaben von den ursprünglichen 28 % für
```
Auch bei `%` bitte immer mit Leerzeichen.

2022-12-05 15:06 UTC, MaKleSoft commented on blog/midijob/index.md
> +aber **keine weiteren Kosten** zu fürchten (**siehe Kasten**).
```suggestion
aber **keine weiteren Kosten** zu befürchten.
```

2022-12-05 15:06 UTC, MaKleSoft commented on blog/midijob/index.md
> +> Dem Grundfreibetrag und Werbungskostenpauschale sei Dank müssen die meißten Angestellten im unteren
```suggestion
> Dem Grundfreibetrag und der Werbungskostenpauschale sei Dank müssen die meisten Angestellten im unteren
```

2022-12-05 15:06 UTC, MaKleSoft commented on blog/midijob/index.md
> +> 960€/Monat und wird regelmäßig erhöht.
```suggestion
> 960 € / Monat und wird regelmäßig erhöht.
```

2022-12-05 18:02 UTC, Lorenz147 commented
Und wie komme ich nun an den Artikel?

Von: Martin Kleinschrodt ***@***.***>
Gesendet: Montag, 5. Dezember 2022 16:06
An: pentacode/site ***@***.***>
Cc: Lorenz Strasser ***@***.***>; Mention ***@***.***>
Betreff: Re: [pentacode/site] Midijobs (PR #67)


@MaKleSoft requested changes on this pull request.

Sehr schön! Gut recherchiert und schön geschrieben. Bitte noch ein bisschen besser auf Rechtschreibung achten (Spellcheck aktiviert?). Was das Thema Meldung angeht kenn ich mich auch nicht aus. Vielleicht kann @Lorenz147<https://github.com/Lorenz147> das weiterhelfen, ansonsten kannst du das Thema von mir aus auch einfach unterschlagen - der Artikel hat so schon genug Substanz meine ich.

________________________________

In blog/midijob/index.md<https://github.com/pentacode/site/pull/67#discussion_r1039703856>:

> +    - Ratgeber



+---



+



+Der "Minijob" aka. die geringfügige Beschäftigung ist in aller Munde - doch



+haben Sie schon einmal etwas von einem "Midijob" gehört? In diesem kurzen



+Artikel erfahren Sie alle relevanten Informationen zur **Zwischenstufe zwischen



+Minijob und Vollzeitanstellung**, seine Vorteile und warum dieses



+Anstellungsverhältnis Sie und ihre Mitarbeitern entlasten kann.



+



+## Ursprung



+



+Der **Midijob** - oder das **Beschäftigungsverhältnis im Übergangsbereich** -



+existiert in seiner heutigen Form seit 2003 in Deutschland. Eingeführt im Zuge



+der Hartz-Reformen sollte er einen Anreiz für Beschäftigungen bieten, deren



+Entgelt nur leicht über der Minijobgrenze liegt. Dazu werden progressiv in der



+Spanne **zwischen 520€ - 1.600€ Sozialversicherungsbeiträge langsam angehoben**, um


⬇️ Suggested change

-Spanne **zwischen 520€ - 1.600€ Sozialversicherungsbeiträge langsam angehoben**, um



+Spanne **zwischen 520 € - 1.600 € Sozialversicherungsbeiträge langsam angehoben**, um



Bitte immer ein Leerzeichen zwischen Betrag und Euro-Zeichen.

________________________________

In blog/midijob/index.md<https://github.com/pentacode/site/pull/67#discussion_r1039705046>:

> +Entgelt nur leicht über der Minijobgrenze liegt. Dazu werden progressiv in der



+Spanne **zwischen 520€ - 1.600€ Sozialversicherungsbeiträge langsam angehoben**, um



+sicherzustellen, dass der Nettoverdienst beim Verlassen der Minijobgrenze nicht



+am Ende niedriger ausfällt als zuvor.



+



+## Was macht den Midijob aus?



+



+Als Midijob gilt ein Beschäftigungsverhältnis dann, wenn:



+- Das durchschnittliche monatliche Entgelt zwischen 520€ und 1.600€ liegt



+- Der Mitarbeiter langfristig (mindestens 3 Monate) angestellt ist



+



+Im Gegensatz zum Minijob unter 520€ ist der **Midijob sowohl Steuer - als auch



+sozialversicherungspflichtig**. Das bedeutet, dass er bei den



+Versicherungsträgern angemeldet werden muss, mehr dazu



+[hier](site/blog/midijob/#zu-beachten). Dafür ist der Arbeitnehmer aber auch



+vollständig versicht und hat Anrecht auf alle Sozialansprüche, welche der


⬇️ Suggested change

-vollständig versicht und hat Anrecht auf alle Sozialansprüche, welche der



+vollständig versichert und hat Anrecht auf alle Sozialansprüche, welche der



________________________________

In blog/midijob/index.md<https://github.com/pentacode/site/pull/67#discussion_r1039706811>:

> +auch -nehmer lohnen.



+



+### Für Arbeitgeber



+



+Da die Abgabenlast zwischen Arbeitsgeber und -nehmer nun



+aufgeteilt wird, sinkt der Anteil der Sozialabgaben von den ursprünglichen 28% für



+Minijobber, auf etwa 20% bei 1.600€ Entgelt ab. Somit sinken die relativen



+Kosten für die Arbeitskraft beim Heben über die 520€ Grenze.



+



+### Für Arbeitnehmer



+



+Zwar sind Arbeitnehmer in einem Midijobverhältnis gezwungen einen Teil des



+Sozialversicherungsbeitrags selbst zu zahlen und auch Lohnsteuer zu entrichten -



+das hört sich aber dramatischer an, als es ist. Durch die gestaffelte Erhöhung



+der Sozialbeiträge erhöhen sich die Kosten nur leicht, besonders im unteren



+Bereich der Gleitzone. Die Lohnsteuer hingegen ist zustäzlich abhängig von der Steuerklasse, im unteren Bereich der Gleitzone haben die meißten Arbeitnehmer dadurch


⬇️ Suggested change

-Bereich der Gleitzone. Die Lohnsteuer hingegen ist zustäzlich abhängig von der Steuerklasse, im unteren Bereich der Gleitzone haben die meißten Arbeitnehmer dadurch



+Bereich der Gleitzone. Die Lohnsteuer hingegen ist zusätzlich abhängig von der Steuerklasse, im unteren Bereich der Gleitzone haben die meisten Arbeitnehmer dadurch



________________________________

In blog/midijob/index.md<https://github.com/pentacode/site/pull/67#discussion_r1039709217>:

> +sozialversicherungspflichtig**. Das bedeutet, dass er bei den



+Versicherungsträgern angemeldet werden muss, mehr dazu



+[hier](site/blog/midijob/#zu-beachten). Dafür ist der Arbeitnehmer aber auch



+vollständig versicht und hat Anrecht auf alle Sozialansprüche, welche der



+typische Minijobber misst.



+



+## Vorteile eines Midijobverhältnisses



+



+Das Anmelden eines Midijobbers ist zwar etwas umständlicher als bei einem



+Minijobber - das Arbeitsverhältnis kann sich jedoch sowohl für Arbeitgeber, als



+auch -nehmer lohnen.



+



+### Für Arbeitgeber



+



+Da die Abgabenlast zwischen Arbeitsgeber und -nehmer nun



+aufgeteilt wird, sinkt der Anteil der Sozialabgaben von den ursprünglichen 28% für


⬇️ Suggested change

-aufgeteilt wird, sinkt der Anteil der Sozialabgaben von den ursprünglichen 28% für



+aufgeteilt wird, sinkt der Anteil der Sozialabgaben von den ursprünglichen 28 % für



Auch bei % bitte immer mit Leerzeichen.

________________________________

In blog/midijob/index.md<https://github.com/pentacode/site/pull/67#discussion_r1039709997>:

> +



+### Für Arbeitgeber



+



+Da die Abgabenlast zwischen Arbeitsgeber und -nehmer nun



+aufgeteilt wird, sinkt der Anteil der Sozialabgaben von den ursprünglichen 28% für



+Minijobber, auf etwa 20% bei 1.600€ Entgelt ab. Somit sinken die relativen



+Kosten für die Arbeitskraft beim Heben über die 520€ Grenze.



+



+### Für Arbeitnehmer



+



+Zwar sind Arbeitnehmer in einem Midijobverhältnis gezwungen einen Teil des



+Sozialversicherungsbeitrags selbst zu zahlen und auch Lohnsteuer zu entrichten -



+das hört sich aber dramatischer an, als es ist. Durch die gestaffelte Erhöhung



+der Sozialbeiträge erhöhen sich die Kosten nur leicht, besonders im unteren



+Bereich der Gleitzone. Die Lohnsteuer hingegen ist zustäzlich abhängig von der Steuerklasse, im unteren Bereich der Gleitzone haben die meißten Arbeitnehmer dadurch



+aber **keine weiteren Kosten** zu fürchten (**siehe Kasten**).


⬇️ Suggested change

-aber **keine weiteren Kosten** zu fürchten (**siehe Kasten**).



+aber **keine weiteren Kosten** zu befürchten.



________________________________

In blog/midijob/index.md<https://github.com/pentacode/site/pull/67#discussion_r1039710865>:

> +Zwar sind Arbeitnehmer in einem Midijobverhältnis gezwungen einen Teil des



+Sozialversicherungsbeitrags selbst zu zahlen und auch Lohnsteuer zu entrichten -



+das hört sich aber dramatischer an, als es ist. Durch die gestaffelte Erhöhung



+der Sozialbeiträge erhöhen sich die Kosten nur leicht, besonders im unteren



+Bereich der Gleitzone. Die Lohnsteuer hingegen ist zustäzlich abhängig von der Steuerklasse, im unteren Bereich der Gleitzone haben die meißten Arbeitnehmer dadurch



+aber **keine weiteren Kosten** zu fürchten (**siehe Kasten**).



+



+So zeigt sich, dass besonders im unteren Bereich der Gleitzone für den



+Arbeitnehmer kaum zusätzliche Kosten anfallen - sie haben aber den identischen



+Anspruch auf Sozialleistungen wie regulär Angestellte Mitarbeiter - unabhängig



+ob das Entgelt 521€ oder 1.600€ ist. **So haben Midijobber im Gegensatz zu



+Minijobbern Anspruch auf alle Leistungen der Kranken- Pflege- und



+Arbeitslosenversicherung!** Ein klares Upgrade zur auschließlichen



+Renten [...]

2022-12-17 11:09 UTC, J0hhny commented
Aspekt zur Meldung rausgenommen
Rechtschreibung überarbeitet
Kleinen Schluss geschrieben

Sollte an sich soweit fertig sein zum releasen.

2023-01-12 18:52 UTC, J0hhny commented
@MaKleSoft 
Ist fertig und alle Verbesserungen integriert.

Problem: Mir wird immer noch "Requested changes must be addressed to merge this pull request" bei GitHub angezeigt angezeigt obwohl ich alle als behoben ausgewählt habe.

2023-01-12 18:53 UTC, J0hhny commented
Kann also keinen Merge anfragen

2023-01-14 07:46 UTC, MaKleSoft commented
@J0hhny Du kannst unter "Reviewers" auf "Re-Request Review" gehen.

2023-01-14 07:46 UTC, MaKleSoft approved these changes

2023-01-14 07:47 UTC, merged