Digitale arbeitsunfähigkeitsbescheinigung
pentacode/site pull request #68
Opened 2022-12-02 16:43 UTC by J0hhny

Artikel zu kommenden Arbeitsunfähigkeitsbescheinigung. Das Integrationsbeispiel in Pentacode fehlt noch - **also noch nicht fertig**.

Nur hochgeladen um bei Interesse schonmal drüber zu lesen.

2022-12-05 15:18 UTC, MaKleSoft requested changes
Auch hier wieder top recherchiert und geschrieben. Gefällt mir echt gut! Den Pentacode-Teil kannst du erstmal auslassen, das es da aktuell einfach noch keine Integration gibt. Können wir aber evtl irgendwann nachtragen.

2022-12-05 15:18 UTC, MaKleSoft commented on blog/digitale-arbeitsunfähigkeitbescheinigung/index.md
> +**Meldepflicht:** Wie bisher muss der Arbeitnehmer den Arbeitgeber über eine Arbeitsunfähigkeit so früh wie möglich informieren. **Ihre Mitarbeiter müssen Sie also wie bisher über eine AU informieren
```suggestion
**Meldepflicht:** Wie bisher muss der Arbeitnehmer den Arbeitgeber über eine Arbeitsunfähigkeit so früh wie möglich informieren. **Ihre Mitarbeiter müssen Sie also wie bisher über eine AU informieren**.
```

2022-12-05 15:18 UTC, MaKleSoft commented on blog/digitale-arbeitsunfähigkeitbescheinigung/index.md
> +eingerichtet wurde.
Hier wären ein, zwei Verlinkungen super.

2022-12-05 15:18 UTC, MaKleSoft commented on blog/digitale-arbeitsunfähigkeitbescheinigung/index.md
> +finden Sie weitere Informationen zum Fragebogen.
```suggestion
Wenn Sie bereits den [Personalfragebogen](hilfe/handbuch/mitarbeiter/dokumente/#personalfragebogen) von Pentacode nutzen **ändert
sich nichts für Sie** - die Krankenkassendaten werden automatisch Teil des
Dokuments und der Mitarbeiter füllt diese aus und Pentacode speichert sie ab.
Wenn nicht könnte das ein weiterer Grund sein sich dieses Feature genauer
anzuschauen.
```

2022-12-05 15:18 UTC, MaKleSoft commented on blog/digitale-arbeitsunfähigkeitbescheinigung/index.md
> +eines Arbeitsunfalls erfolgt ist.
```suggestion
- Name des/der Beschäftigten.
- Beginn und Ende der Arbeitsunfähigkeit.
- Datum der ärztlichen Feststellung der Arbeitsunfähigkeit.
- Kennzeichnung als Erst- oder Folgemeldung und die Angabe ob die AU als Folge
eines Arbeitsunfalls erfolgt ist. 
```

2022-12-05 15:18 UTC, MaKleSoft commented on blog/digitale-arbeitsunfähigkeitbescheinigung/index.md
> +mehr einfordern - und sollten dies auch nicht tuen, falls der Mitarbeiter Ihnen
```suggestion
mehr einfordern - und sollten dies auch nicht tun, falls der Mitarbeiter Ihnen
```

2022-12-05 15:18 UTC, MaKleSoft commented on blog/digitale-arbeitsunfähigkeitbescheinigung/index.md
> +--- Zusätzliche Information der Nutzung
Kommt hier noch was? Ansonsten nicht vergessen rauszunehmen.

2022-12-05 18:02 UTC, Lorenz147 commented
Ich bin hier übers Wochenende ums Verreckennicht in Github reingekommen um den Artikel zu lesen. Wollte einfach nicht laden.
Mache ich was falsch?

Von: Martin Kleinschrodt ***@***.***>
Gesendet: Montag, 5. Dezember 2022 16:19
An: pentacode/site ***@***.***>
Cc: Lorenz Strasser ***@***.***>; Review requested ***@***.***>
Betreff: Re: [pentacode/site] Digitale arbeitsunfähigkeitsbescheinigung (PR #68)


@MaKleSoft requested changes on this pull request.

Auch hier wieder top recherchiert und geschrieben. Gefällt mir echt gut! Den Pentacode-Teil kannst du erstmal auslassen, das es da aktuell einfach noch keine Integration gibt. Können wir aber evtl irgendwann nachtragen.

________________________________

In blog/digitale-arbeitsunfähigkeitbescheinigung/index.md<https://github.com/pentacode/site/pull/68#discussion_r1039720240>:

> +author: jseidel



+categories:



+    - Aktuelles



+---



+



+Ab Anfang nächsten Jahres wird in ganz Deutschland die elektronische



+Arbeitsunfähigkeitsbescheinigung (eAU) eingeführt - einfach gesagt die digitale Version des gelben Zettels. Neben dieser einfachen Umstellung von Papierformat auf



+digitale Bescheinigung erfolgt jedoch auch ein rechtlicher Wechsel zu Kosten des



+Arbeitgebers. Dieser muss von nun an die eAU selbstständig bei der Krankenkasse einholen. Hört sich nach viel Arbeit an - einmal erlernt ist diese Anforderung



+aber nicht wirklich komplizierter und eröffnet auch wieder Chancen einer



+effektiveren Dokumentenverwaltung. **Im folgenden Artikel erfahren Sie alles, was



+Sie als Arbeitgeber zur neuen eAU wissen müssen**.



+



+## Das bleibt unverändert



+



+**Meldepflicht:** Wie bisher muss der Arbeitnehmer den Arbeitgeber über eine Arbeitsunfähigkeit so früh wie möglich informieren. **Ihre Mitarbeiter müssen Sie also wie bisher über eine AU informieren**


⬇️ Suggested change

-**Meldepflicht:** Wie bisher muss der Arbeitnehmer den Arbeitgeber über eine Arbeitsunfähigkeit so früh wie möglich informieren. **Ihre Mitarbeiter müssen Sie also wie bisher über eine AU informieren**



+**Meldepflicht:** Wie bisher muss der Arbeitnehmer den Arbeitgeber über eine Arbeitsunfähigkeit so früh wie möglich informieren. **Ihre Mitarbeiter müssen Sie also wie bisher über eine AU informieren**.



________________________________

In blog/digitale-arbeitsunfähigkeitbescheinigung/index.md<https://github.com/pentacode/site/pull/68#discussion_r1039722689>:

> +



+## Was sich für Sie ändert



+



+**Vorlagepflicht:** Bisher hatte der Arbeitnehmer auch eine Vorlagepflicht, er



+musste also die Bescheinigung der AU beim Arbeitgeber vorlegen. Diese Pflicht



+entfällt nun, nach dem Arztbesuch hat der Arbeitnehmer seine Pflicht erfüllt und



+der **Arbeitgeber muss eigenständig die AU Bescheinigung bei der Krankenkasse



+einholen.**



+



+### Wie kontaktieren Sie die Krankenkasse?



+



+Um die AU Bescheinigung einer ihrer Mitarbeiter einzuholen müssen Sie direkt mit



+der Krankenkasse in Kontakt treten. Wie der Name eAU schon verrät erfolgt das



+vollständig digital. In Kontakt treten Sie dabei entweder direkt über ihre Entgeldabrechnungssoftware



+oder über die supplementäre Software **ITSG**, welche speziell für diesen Zweck



+eingerichtet wurde.



Hier wären ein, zwei Verlinkungen super.

________________________________

In blog/digitale-arbeitsunfähigkeitbescheinigung/index.md<https://github.com/pentacode/site/pull/68#discussion_r1039725065>:

> +Wenn Sie bereits die **Personalfragebogen** von Pentacode nutzen **ändert



+sich nichts für Sie** - die Krankenkassendaten werden automatisch Teil des



+Dokuments und der Mitarbeiter füllt diese aus und Pentacode speichert sie ab.



+Wenn nicht könnte das ein weiterer Grund sein sich dieses Feature genauer



+anzuschauen - [hier](hilfe/handbuch/mitarbeiter/dokumente/#personalfragebogen)



+finden Sie weitere Informationen zum Fragebogen.


⬇️ Suggested change

-Wenn Sie bereits die **Personalfragebogen** von Pentacode nutzen **ändert



-sich nichts für Sie** - die Krankenkassendaten werden automatisch Teil des



-Dokuments und der Mitarbeiter füllt diese aus und Pentacode speichert sie ab.



-Wenn nicht könnte das ein weiterer Grund sein sich dieses Feature genauer



-anzuschauen - [hier](hilfe/handbuch/mitarbeiter/dokumente/#personalfragebogen)



-finden Sie weitere Informationen zum Fragebogen.



+Wenn Sie bereits den [Personalfragebogen](hilfe/handbuch/mitarbeiter/dokumente/#personalfragebogen) von Pentacode nutzen **ändert



+sich nichts für Sie** - die Krankenkassendaten werden automatisch Teil des



+Dokuments und der Mitarbeiter füllt diese aus und Pentacode speichert sie ab.



+Wenn nicht könnte das ein weiterer Grund sein sich dieses Feature genauer



+anzuschauen.



________________________________

In blog/digitale-arbeitsunfähigkeitbescheinigung/index.md<https://github.com/pentacode/site/pull/68#discussion_r1039726340>:

> +-Name des/der Beschäftigten.



+-Beginn und Ende der Arbeitsunfähigkeit.



+-Datum der ärztlichen Feststellung der Arbeitsunfähigkeit.



+-Kennzeichnung als Erst- oder Folgemeldung und die Angabe ob die AU als Folge



+eines Arbeitsunfalls erfolgt ist.


⬇️ Suggested change

--Name des/der Beschäftigten.



--Beginn und Ende der Arbeitsunfähigkeit.



--Datum der ärztlichen Feststellung der Arbeitsunfähigkeit.



--Kennzeichnung als Erst- oder Folgemeldung und die Angabe ob die AU als Folge



-eines Arbeitsunfalls erfolgt ist.



+- Name des/der Beschäftigten.



+- Beginn und Ende der Arbeitsunfähigkeit.



+- Datum der ärztlichen Feststellung der Arbeitsunfähigkeit.



+- Kennzeichnung als Erst- oder Folgemeldung und die Angabe ob die AU als Folge



+eines Arbeitsunfalls erfolgt ist.



________________________________

In blog/digitale-arbeitsunfähigkeitbescheinigung/index.md<https://github.com/pentacode/site/pull/68#discussion_r1039728318>:

> +



+>Wir empfehlen Ihnen schwer diese Funktion auch **jetzt schon zu testen** - so gehen



+>Sie sicher, dass Sie zum Anfang des neuen Jahres mit der Software und dem



+>Prozess vertraut sind und Sie keine Überraschung erwartet.



+



+## Wo bleibt die alte AU erhalten?



+



+Da das System der eAU noch neu ist, werden nicht alle Zentren der



+Gesundheitsversorgung von Anfang an daran teilhaben. Dies gilt zum einen **für Privatärzte und



+Privatkliniken, sowie Ärzte im Ausland und generell alle privat Versicherten**.



+Auch **Rehabilitationskliniken, Physio- und Psychotherapeuten** werden vorest



+ihre AU weiterhin als 'gelben Zettel' ausstellen.



+Auch erhält der Arbeitnehmer weiterhin eine Bescheinigung über seine AU beim



+diagnostizierenden Arzt - diese dient der rechtlichen Sicherheit, dass er seiner



+Meldepflicht nachgegangen ist. Als Arbeitgeber dürfen Sie diese nun aber nicht



+mehr einfordern - und sollten dies auch nicht tuen, falls der Mitarbeiter Ihnen


⬇️ Suggested change

-mehr einfordern - und sollten dies auch nicht tuen, falls der Mitarbeiter Ihnen



+mehr einfordern - und sollten dies auch nicht tun, falls der Mitarbeiter Ihnen



________________________________

In blog/digitale-arbeitsunfähigkeitbescheinigung/index.md<https://github.com/pentacode/site/pull/68#discussion_r1039730216>:

> +



+**Vorlagepflicht:** Bisher hatte der Arbeitnehmer auch eine Vorlagepflicht, er



+musste also die Bescheinigung der AU beim Arbeitgeber vorlegen. Diese Pflicht



+entfällt nun, nach dem Arztbesuch hat der Arbeitnehmer seine Pflicht erfüllt und



+der **Arbeitgeber muss eigenständig die AU Bescheinigung bei der Krankenkasse



+einholen.**



+



+### Wie kontaktieren Sie die Krankenkasse?



+



+Um die AU Bescheinigung einer ihrer Mitarbeiter einzuholen müssen Sie direkt mit



+der Krankenkasse in Kontakt treten. Wie der Name eAU schon verrät erfolgt das



+vollständig digital. In Kontakt treten Sie dabei entweder direkt über ihre Entgeldabrechnungssoftware



+oder über die supplement [...]

2023-01-14 07:51 UTC, MaKleSoft commented
@J0hhny Was ist hier der Status? Ist das bereit zum Mergen?

2023-01-16 16:49 UTC, J0hhny commented
Jap ist jetzt mergebereit - einzig die Quelle des Bilds am Ende weiß ich noch nicht genau wie ich die am besten einfügen soll - ist bis jetzt nur in <i>italic</i>

2023-01-17 07:44 UTC, MaKleSoft approved these changes
Top! 👍

2023-01-17 07:44 UTC, merged