Einstellungen zuschläge
pentacode/site pull request #71
Opened 2023-02-06 11:28 UTC by J0hhny

Hier die erste Version des Hilfsartikels zu Einstellungen>Zuschläge.
Noch nicht fertig, es gibt noch einige Unklarheiten:

- Mir ist der Unterschied zwischen Prozent maximal vs prozent standard noch nicht klar - geht es hier um die kummulierung mit anderen Zuschlägen?
-  Die gesetzlichen SFN-Zuschläge sind nicht standardmäßig enthalten, richtig? Wäre es nicht sinnvoll diese als Standard festzulegen oder zumindest den Button "SFN-Zuschläge hinzufügen" zu integrieren - da das die wahrscheinlichkeit die SFN Zuschläge zu vergessen/falsch einzugeben reduzieren würde?
- Bei "Mindestdauer Schicht" wird nicht klar ob diese dann für die ganze Schicht gilt oder nur alles ab der Mindestanzahl - also M1 arbeitet samstags 6 h - Mindestdauer sind 4 h für den Samstagszuschlag - kriegt er jetzt schon alle 6h zuschlag und nicht nur die 2 die drüber sind? Wäre logisch geht aber nicht klar hervor da z.B für Überstunden-Zuschläge man ja nur wollen würde, dass alles **Über** der Mindestzeit mit Zuschlägen entlohnt wird.
- Wenn wir bei "Hat Vorrang vor..." einen Zuschlag auswählen schließt sich das Fenster immer direkt, was relativ nervig ist, wenn man mehrere Auswählen möchte.

Am besten besprechen wir das später am Telefon.

2023-02-06 12:02 UTC, MaKleSoft commented
> Mir ist der Unterschied zwischen Prozent maximal vs prozent standard noch nicht klar - geht es hier um die kummulierung mit anderen Zuschlägen?

Prozent maximale Prozentwert, der im Vertrag eines Mitarbeiters angegeben werden kann. Standard ist einfach der Anfangswert, der beim hinzufügen eines Zuschlags ausgewählt ist.

> Die gesetzlichen SFN-Zuschläge sind nicht standardmäßig enthalten, richtig? Wäre es nicht sinnvoll diese als Standard
> festzulegen oder zumindest den Button "SFN-Zuschläge hinzufügen" zu integrieren - da das die wahrscheinlichkeit die SFN
> Zuschläge zu vergessen/falsch einzugeben reduzieren würde?

Doch, Standard-SFN-Zuschläge werden automatisch beim Anlegen eines neuen Kunden hinzugefügt. Bei Bestandskunden werden dies auch automatisch migriert (ist aktuell nur in der Demoumgebung nicht der Fall).

> Bei "Mindestdauer Schicht" wird nicht klar ob diese dann für die ganze Schicht gilt oder nur alles ab der Mindestanzahl - also M1 arbeitet samstags 6 h - Mindestdauer sind 4 h für den Samstagszuschlag - kriegt er jetzt schon alle 6h zuschlag und nicht nur die 2 die drüber sind? Wäre logisch geht aber nicht klar hervor da z.B für Überstunden-Zuschläge man ja nur wollen würde, dass alles Über der Mindestzeit mit Zuschlägen entlohnt wird.

Er kriegt den ganzen Zuschlagszeitraum ausbezahlt.

2023-02-06 12:17 UTC, MaKleSoft requested changes

2023-02-06 12:17 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Zuschläge sind eine Möglichkeit ihre Mitarbeiter für bestimmmte Schichten extra zu entlohnen. Generell sollte man dabei zwischen den gesetzlich verpflichteten SFN (Sonntag, Feiertag, Nachts) und weit
```suggestion
Zuschläge sind eine Möglichkeit, Ihre Mitarbeiter für Arbeit an bestimmten Tagen und in bestimmten Zeiträumen extra zu entlohnen. Generell sollte man dabei zwischen den gesetzlich bestimmten SFN (Sonntag, Feiertag, Nachts) und weiteren frei definierten Zuschlägen (bspw. für Samstagsschichten) unterscheiden. Diese Unterscheidung ist besonders wichtig, da die gesetzlichen SFN Zuschläge beitragsfrei ausgezahlt werden können. 
```

2023-02-06 12:17 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Klicken sie auf {% button icon = "plus", label = "Neue Zuschlagsart"%}** um einen neuen Typen Zuschlagsklasse zu erstellen. Anschließend öffnet sich ein Dialogsfeld in welchem Sie die Eigenschaften d
```suggestion
Klicken sie auf {% button icon = "plus", label = "Neue Zuschlagsart"%} um eine neuen Zuschlagsart zu erstellen. Anschließend öffnet sich ein Bearbeitungsdialog in welchem Sie die Eigenschaften des Zuschlags definieren können. 
```

2023-02-06 12:17 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Hier können Sie auswählen an welchen Daten der Zuschlag den zugeteilten Mitarbeitern automatisch angerechnet werden soll.
```suggestion
Hier können Sie auswählen, an welchen Tage der Zuschlag zu Wirkung kommen soll. 
```

2023-02-06 12:17 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Sollten Sie einen speziellen Zuschlagssatz für bestimmte Feiertage gewähren wollen - hier können Sie dies. Wählen Sie einfach die gewünschten Feiertage aus der Liste aus.
```suggestion
Sollten Sie einen speziellen Zuschlagssatz für bestimmte Feiertage gewähren wollen, können Sie dies hier tun. Wählen Sie einfach die gewünschten Feiertage aus der Liste aus. 
```

2023-02-06 12:17 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Sollten Zuschläge erst ab einer gewissen Schichtdauer angerechnet werden, können Sie dies hier auswählen. Geben Sie dazu einfach die Mindestdauer in das Feld ein (beim Überschreiten der Schichtlänge
```suggestion
Sollten Zuschläge erst ab einer gewissen Mindestdauer im Zuschlagszeitraum angerechnet werden, können Sie dies hier auswählen. Geben Sie dazu einfach die Mindestdauer in das Feld ein.
```

2023-02-06 12:17 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Sollten Zuschläge erst ab einer gewissen Schichtdauer angerechnet werden, können Sie dies hier auswählen. Geben Sie dazu einfach die Mindestdauer in das Feld ein (beim Überschreiten der Schichtlänge
Achtung! Die Mindestdauer bezieht sich auf die Mindestdauer im Zuschlagszeitraum! Also z.b. bei Nachtzuschlägen. Mit Überstunden hat das nichts zu tun. Erklär ich dir aber gerne nochmal am Telefon.

2023-02-06 12:17 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Wenn Sie einen bestehenden Zuschlag bearbeiten wollen klicken Sie auf das **...-Symbol** neben diesem und wählen **Bearbeiten** aus. Sie gelangen anschließend in das gleiche Menü, wie unter [**Neue Z
```suggestion
Wenn Sie einen bestehenden Zuschlag bearbeiten wollen klicken Sie den {% button icon="ellipsis-h" %} neben diesem und wählen **Bearbeiten** aus. Sie gelangen anschließend in das gleiche Menü, wie unter [**Neue Zuschläge**](#neue-zuschlagsart-hinzufügen) beschrieben. 
```
Das Button-Format bitte auch bei Menüpunkten (z.b. Löschen, Bearbeiten etc.)

2023-02-07 13:18 UTC, J0hhny commented
Soweit alles geklärt. Nur noch:
- Passt die Formulierung am Anfang mit den SFN Zuschlägen? Oder sollen diese gar nicht bearbeitbar sein? (wieder Vermeidung von Fehlern)
- Weiterhin das Problem, dass sich die Zuschlagsart schließt wenn ich eine andere Art bei "Hat Vorrang vor..." eingebe.

2023-02-09 08:28 UTC, MaKleSoft requested changes
Eine Runden an Änderungen noch, dann sollte es so passen :)

2023-02-09 08:28 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +>**Achtung!** Verändern Sie die grundangelegten SFN-Zuschlagsarten nur, wenn Sie wissen, was Sie tuen - Veränderungen an diesen können schnell in Lohnverstößen enden!
```suggestion
Die in [§ 3b des Einkommenssteuergesetzes (EStG)](https://www.gesetze-im-internet.de/estg/__3b.html) definierten SFN (Sonntags-, Feiertags- und Nachts-) Zuschläge werden für Sie automatisch angelegt. Solange für Ihr Unternehmen also keine gesonderten Regeln gelten, sollten Sie in diesem Bereich normalerweise keine Anpassungen machen müssen.

**Sollten Sie dennoch Änderungen vornehmen wollen (z.B.: eine Anpassung der Zuschlagszeiträume), dann beachten Sie bitte, dass alle Zuschläge, die über den in § 3b EStG definierten Rahmen hinausgehen, beitragspflichtig sind!**
```

2023-02-09 08:28 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +> **Achtung!** Zuschläge außerhalb der gesetzlich vorgeschriebenen SFN-Zuschläge können nicht beitragsfrei abgerechnet werden - dies würde einer Abgabenhinterziehung gleichkommen!
```suggestion
> **Achtung!** Zuschläge außerhalb der [gesetzlich definierten SFN-Zuschläge](https://www.gesetze-im-internet.de/estg/__3b.html) können nicht beitragsfrei abgerechnet werden - dies würde einer Abgabenhinterziehung gleichkommen!
```

2023-02-09 08:28 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Hier wird bestimmt ob der Zuschlag betragsfrei abgerechnet werden kann. **Generell gilt, dass nur gesetzlich verpflichtete SFN-Zuschläge bis zu 25€/h beitragsfrei sind.** Sollte es sich um einen SFN-
```suggestion
Hier wird bestimmt ob der Zuschlag betragsfrei abgerechnet werden kann. **Generell gilt, dass nur gesetzlich [gesetzlich definierte SFN-Zuschläge](https://www.gesetze-im-internet.de/estg/__3b.html) bis zu 25€/h beitragsfrei sind.** Sollte es sich um einen SFN-Zuschlag handeln haben Sie normalerweise natürlich Interesse daran diesen so lange wie möglich beitragsfrei abzurechnen. Deshalb sollte dieses Feld normalerweise mit 25 € / Std. für SFN-Zuschläge und 0 € / Std. für restliche Zuschläge ausgefüllt werden. 
```

Achtung: SFN-Zuschläge sind **nicht** "gesetzlich verpflichtend"! Ob Zuschläge gezahlt werden oder nicht und in welcher Höhe, darf der Arbeitgeber schon frei entscheiden (außer es ist im Tarifvertrag definiert).

2023-02-09 08:28 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Was passiert wenn ein Mitarbeiter einer zuschlagsberechtigten Schicht zugeteilt ist, diese aber nicht antreten kann weil er erkrankt oder beurlaubt ist? Zwar dürfen diese nicht angetretenen Zuschlags
```suggestion
Nach den im [Entgeldfortzahlungsgesetz](https://www.gesetze-im-internet.de/entgfg/__4.html) definierten Regelungen, sind SFN-Zuschläge grundsätzlich auch im Lohnfortzahlungsfall zu gewähren. In diesem Fall berechnet Pentacode für Sie automatisch die entsprechenden Stundenwerte basierend auf den Durchschnittswerten der letzten 13 Wochen. **Achtung: Aus Fehltagen entstehende Zuschläge sind in jedem Fall beitragspflichtig!**
```

2023-02-09 08:28 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Was passiert wenn ein Mitarbeiter einer zuschlagsberechtigten Schicht zugeteilt ist, diese aber nicht antreten kann weil er erkrankt oder beurlaubt ist? Zwar dürfen diese nicht angetretenen Zuschlags
Falls Zuschläge bezahlt werden ist die Fortzahlung tatsächlich gesetzlich vorgeschrieben.

2023-02-09 08:28 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Um die nun erstellten Zuschläge Mitarbeitern zuzuordnen, wählen Sie den Reiter **Mitarbeiter** aus und navigieren zu den **Verträgen**. Unter **Zuschläge** können Sie nun die Zuschläge auswählen, die
Der Link funktioniert nicht... Bitte Verlinkungen auch immer testen, da schleichen sich immer schnell Tippfehler ein.

2023-02-09 08:28 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Wenn Sie eine Zuschlagsart löschen möchten klicken Sie auf das **...-Symbol** neben dieser und wählen **Löschen** aus.
Auch hier bitte den Button-Stil nutzen.

2023-02-09 08:28 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +Sie möchten eine weitere Zuschlagsart hinzufügen und eine bestehende als Vorlage nutzen? Klicken Sie auf das **...-Symbol** neben der Vorlage und wählen **Duplizieren** aus.
Auch hier bitte den Button-Stil nutzen.

2023-02-13 13:15 UTC, J0hhny commented
Changes integriert und Struktur etwas verschönert - sollte mergebereit sein

2023-02-13 15:17 UTC, MaKleSoft requested changes

2023-02-13 15:17 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +{% figure caption= "Dieser Zuschlag wird den Mitarbeitern nur Samstags von 20 Uhr bis 4 Uhr des folgenden Tages angerechnet."%}
Hier hast du einen Syntaxfehler:

```suggestion
{% figure caption="Dieser Zuschlag wird den Mitarbeitern nur Samstags von 20 Uhr bis 4 Uhr des folgenden Tages angerechnet." %}
```

Bitte auch immer lokal bei dir testen bevor du etwas hochlädst. Zumindest ohne Fehler kompilieren sollte es schon.

2023-02-13 15:17 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/zuschläge/index.md
> +<img src = "samstagnacht.webp">
```suggestion
<img src="samstagnacht.webp">
```
Bitte grundsätzlich keine Leerzeichen um das `=` herum.

2023-02-16 11:51 UTC, J0hhny commented
Kompilierungsfehler behoben - jetzt sollte es mergebereit sein.

2023-02-16 13:03 UTC, MaKleSoft approved these changes

2023-02-16 13:03 UTC, merged

2023-02-16 13:04 UTC, MaKleSoft commented
Gemerged 👍