Update 1.2.4
pentacode/site pull request #72
Opened 2023-02-06 22:24 UTC by J0hhny

Der Updatepost soweit - inhaltlich sollte er fertig sein, es fehlt nur noch die Verlinkung zum Änderungsprotokoll. 
Inhaltlich fiel es mir etwas schwieriger das update "anzupreisen" und "die Essenz einzufangen" einfach weil mir auch die Nutzen des Updates nicht so klar sind wie beim Personalfragebogen/Sofortmeldung.

2023-02-07 14:47 UTC, MaKleSoft requested changes
Zusätzlich zu den anderen Änderungswunschen hätte ich mir hier schon grundsätzlich ein kleines bisschen mehr / schöner ausgeschmückten Text gewünscht. Schau vielleicht nochmal drüber, ob dir noch ein paar schönere Floskeln einfallen. Wäre aber im Notfall auch so passabel ;)

2023-02-07 14:47 UTC, MaKleSoft commented on blog/update_v1.24/index.md
> +Mit Pentacode V. 1.24 helfen wir Ihnen den Bürokratiejungle zu navigieren und wertvolle Zeit bei der Vorbereitung von Lohndaten und co. zu sparen. Dabei haben wir **eine gänzlich überarbeitete Datene
```suggestion
Mit Pentacode V. 1.24 helfen wir Ihnen den Bürokratiedschungel zu navigieren und wertvolle Zeit bei der Vorbereitung von Lohndaten und co. zu sparen. Dabei haben wir **eine gänzlich überarbeitete Datenexportfunktion, viele neue Individualisierungsoptionen sowie viele weitere Verbesserungen & Neuheiten** in Petto, um Ihnen die Vorbereitung der Buchhaltung so einfach wie möglich zu machen.
```

2023-02-07 14:47 UTC, MaKleSoft commented on blog/update_v1.24/index.md
> +title: "Pentacode v1.24: Datenexport und individualisierte Lohnberichte"
```suggestion
title: "Pentacode v1.24: Noch mehr Power im Bereich Lohnvorbereitung und Datenexport"
```

2023-02-07 14:55 UTC, MaKleSoft commented
Ach ja, link zum Änderungsprotokoll: `/hilfe/aenderungsprotokoll/#1.24.0` (v1.24.0 ist in diesem Branch noch nicht aufgeführt, ist aber da sobald der Branch gemerged ist (alternativ kannst du auch `master` hier rein mergen).

2023-02-07 19:37 UTC, J0hhny commented
Noch einmal ein wenig umformuliert - ich hoffe es hört sich jetzt besser an.
Ich werde morgen noch einmal drüber lesen und vielleicht noch ein paar kleine Umformulierungen vornehmen.
Gibt es noch etwas das mehr betont werden sollte im Updatebericht?

2023-02-09 08:38 UTC, MaKleSoft requested changes
Die aktuelle Version gefällt mir gut! Ein paar kleine Änderungen noch dann kann das veröffentlicht werden.

2023-02-09 08:38 UTC, MaKleSoft commented on blog/update_v1.24/index.md
> +Mit Pentacode V. 1.24 helfen wir Ihnen den Bürokratiedschungel besser zu navigieren und wertvolle Zeit bei der Vorbereitung von Lohndaten zu sparen. Dabei werden Ihnen **eine gänzlich überarbeitete D
```suggestion
Mit Pentacode v1.24 helfen wir Ihnen den Bürokratiedschungel besser zu navigieren und wertvolle Zeit bei der Vorbereitung von Lohndaten zu sparen. Dabei werden Ihnen **eine gänzlich überarbeitete Datenexportfunktion, viele neue Individualisierungsoptionen sowie viele weitere Verbesserungen & Neuheiten** helfen, die Früchte einer guten Buchhaltung noch einfacher zu ernten. 
```

2023-02-09 08:38 UTC, MaKleSoft commented on blog/update_v1.24/index.md
> +Der neue Datenexportreiter - das Herzstück unseres neuen Updates. Statt wie zuvor Stammdatenblatt, Lohnberichte, Arbeitszeiten und co. verteilt über die verschiedenen Funktionen Pentacodes suchen zu
```suggestion
Der neue Datenexportreiter - das Herzstück unseres neuen Updates. Statt wie zuvor Stammdatenblatt, Lohnberichte, Arbeitszeiten und co. in verschiedenen Bereichen der Software suchen zu müssen, finden Sie nun alle benötigten Daten gut strukturiert an einem Ort - Sie müssen nur noch auf Download klicken.
```

2023-02-09 08:38 UTC, MaKleSoft commented on blog/update_v1.24/index.md
> +<img src="lohnberichte.gif"/>
Bitte zu den ganzen Bildern noch Alt-Texte hinzufügen. Dabei musst du dir allerdings nicht zu viel Mühe geben, geht hauptsächlich darum, überhaupt einen Alt-Text zu haben wegen SEO. Also einfach eine kurze Beschreibung, was in dem Bild zu sehen ist. Z.B.:

```suggestion
<img src="lohnberichte.gif" alt="Animierter Screenshot der Datenexport-funktion." />
```

2023-02-09 08:40 UTC, MaKleSoft commented on blog/update_v1.24/index.md
> +cover: datenexport.webp
Hier bitte auch noch `coverAlt` hinzufügen - damit das Titelbild auch einen alt-text hat:

```yml
coverAlt: blah
```

2023-02-09 13:34 UTC, J0hhny commented
fixes integriert - sollte bereit zum publishen sein.

2023-02-10 15:04 UTC, MaKleSoft approved these changes

2023-02-10 15:07 UTC, merged