Datenexport
pentacode/site pull request #73
Opened 2023-02-09 16:29 UTC by J0hhny

Erste Version vom Datenexport Hilfsartikel.
Noch nicht ganz fertig.
- Arbeitszeitnachweis noch rausnehmen aus Mitarbeiter überpunkt
- Korrekturlesen

2023-02-13 12:40 UTC, J0hhny commented
Überarbeitung noch ausstehend!

2023-02-21 14:03 UTC, J0hhny commented
Überarbeitet - ein paar offene Punkte gibt es aber noch:
- Fällt dir eine gute option ein icons in figure captions einzufügen? Konnte auf die schnelle online dazu nichts finden.
- @Weißt du ob bei einer Prüfung die digital signierten und gespeicherten Lohnabrechnungen ausreichend sind oder ob man die immer noch ausgedruckt braucht? (bin ich grade am recherchieren)
- Was genau bedeuten die verschiedenen Zeichen beim Export bestimmter Lohnformate? Sicherlich verschiedene "Schweregrade" (siehe Screenshot) von Problemen aber funktioniert der Export bei einem z.B garnicht und beim anderen fehlt dann nur was im Lohnprogramm? 
- Es gibt das Problem, dass es keine Scrollleiste gibt bei den Kassenbuch exporten, deshalb habe ich diesen Teil noch nicht ganz fertig gestellt (siehe pentacode>issues)

![manage demo pentacode app_exports_payroll_addison_venue=26 date=2022-12-01 date_from=2023-02-01 date_to=2023-03-01 next=settings%2Faccounting tab=0(iPad Air)](https://user-images.githubusercontent.com/104359585/220366627-b5a47bcd-a942-4f8b-93c0-b1e3a4a0d1e9.png)

hoffentlich alles soweit verständlich!

2023-02-24 12:13 UTC, MaKleSoft commented
> Fällt dir eine gute option ein icons in figure captions einzufügen? Konnte auf die schnelle online dazu nichts finden.

Ne, das geht leider nicht so einfach. In den Captions musst du leider ohne Icons auskommen.

> @weißt du ob bei einer Prüfung die digital signierten und gespeicherten Lohnabrechnungen ausreichend sind oder ob man die immer noch ausgedruckt braucht? (bin ich grade am recherchieren)

Digital ist auf jeden Fall ausreichend.

> Was genau bedeuten die verschiedenen Zeichen beim Export bestimmter Lohnformate? Sicherlich verschiedene "Schweregrade" (siehe Screenshot) von Problemen aber funktioniert der Export bei einem z.B garnicht und beim anderen fehlt dann nur was im Lohnprogramm?

Schwarz sind Informationen und können im Normalfall ignoriert werden, orange sind Warnungen, rot sind Fehler.

> Es gibt das Problem, dass es keine Scrollleiste gibt bei den Kassenbuch exporten, deshalb habe ich diesen Teil noch nicht ganz fertig gestellt (siehe pentacode>issues)

Hab das Ticket gesehen. Wird zeitnah behoben.

2023-02-24 12:33 UTC, MaKleSoft requested changes
Die Optionen "Versenden An" und "Im Dokumentenarchiv" ablegen hast du nur unter "Arbeitszeitennachweis" beschrieben, die Option ist aber auch in anderen Formaten verfügbar. Vielleicht machst du noch einen separaten Abschnitt, der die verschiedenen Formatübergreifenden Exportoptionen beschreibt, jeweils mit Hinweis für welche Formate die Option verfügbar ist.

2023-02-24 12:33 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +Unter Datenexport können Sie Daten von Pentacode zusammengefasst herunterladen und in andere Software übertragen. In den verschiedenen Gebieten von Pentacode finden Sie öfters das {%icon "download"%}
```suggestion
Unter dem Menüpunkt {% button label="Datenexport" icon="download" %} sind alle in Pentacode verfügbaren Datenexporte an einem Ort zusammengefasst. Hier finden Sie verschiede Optionen zum Export von Arbeitszeiten, Lohnberichten und mehr.

> In den verschiedenen Bereichen von Pentacode finden Sie öfters das {%icon "download"%}**-Symbol**, dieses verweist Sie stets in den hier beschriebenen Reiter.
```

2023-02-24 12:33 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +Geben Sie eine Email Adresse in das Feld über {%button label = "**Export starten**" %} ein, um die Lohnberichtsübersicht direkt zu verschicken.
```suggestion
Geben Sie eine Email Adresse in das Feld über {% button label="**Export Starten**" icon="download" %} ein, um die Lohnberichtsübersicht direkt zu verschicken. 
```
Was hatte ich über die einheitliche Formattierung gesagt? 🙃

2023-02-24 12:33 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +In der Lohnbericht-Übersicht, sind die Arbeitsstunden und -tage, sowie Zuschlagsstunden, Mitarbeiteressen und das aktuelle Gehalt in einer tabellarischen Ansicht zusammengefasst. Dieser Ausdruck ist
```suggestion
In der Lohnbericht-Übersicht sind die Arbeitsstunden und -tage, sowie Zuschlagsstunden, Mitarbeiteressen und das aktuelle Gehalt in einer tabellarischen Ansicht zusammengefasst. Dieser Ausdruck ist vor allem für die Übermittlung an Ihr Lohnbüro gut geeignet und dient als Alternative zum direkten Export/Import in Ihr Lohnbuchhaltungs-Programm.
```

2023-02-24 12:33 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +> Im Falle einer Prüfung ist es empfehlenswert, dem Prüfer für eine Stichprobenkontrolle einzelne Ausdrucke der "Lohnabrechnung" zu überlassen. Die offensichtliche Transparenz, Richtigkeit und Glaubw
Bitte **nicht** empfehlen, sachen auszudrucken. Wir wollen doch weg vom Papier! Und dafür haben wir schließlich die Option "Im Dokumentenarchiv ablegen".

2023-02-24 12:33 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +Wählen Sie dazu **Lohnbericht (Detailliert)** aus und geben wieder den gewünschten Zeitraum sowie die Mitarbeiter / Abteilungen ein, für den Sie die detaillierte Lohnübersicht erstellen möchten. Auch
Der Lohnbericht Detailliert enthält zusätzlich:

- Eine List der Abwesenheiten mit Beginn, Ende und Anzahl der Fehltage
- Vertragsveränderungen bzw. Vertragsende, falls in dem Zeitraum vorhanden
- Veränderungen des Arbeitszeitkontos

2023-02-24 12:33 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +Neben den oben genannten Ausdrucken können Sie lohnabrechnungsrelevante Bewegungsdaten auch in verschiedene Lohnbuchhaltungsprogramme exportieren. Wählen Sie dazu das gewünschte Format unter **Lohnbu
```suggestion
Neben den oben genannten Berichten in PDF-Form können Sie lohnabrechnungsrelevante Bewegungsdaten auch in verschiedene Lohnbuchhaltungsprogramme exportieren. Wählen Sie dazu das gewünschte Format unter **Lohnbuchhaltung** aus und gehen Sie genau so vor, wie bei der normalen Lohnabrechnung.
```

2023-02-24 12:33 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +<img src=".webp" />
Bild?

2023-02-24 12:33 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +Um den Arbeitszeitennachweis zu erstellen navigieren Sie in den Reiter **Datenexport** und klicken auf {%button label = "Arbeitszeit-Nachweis"%}. Wählen Sie nun im Kalender erst einmal den Zeitraum a
```suggestion
Um den Arbeitszeitennachweis zu erstellen navigieren Sie in den Reiter **Datenexport** und klicken auf {% button label="Arbeitszeit-Nachweis" %}. Wählen Sie nun im Kalender erst einmal den Zeitraum aus, für den Sie den Nachweis erstellen wollen. Soll es ein **Monatsnachweis** sein, können Sie auch gleich einen ganzen Monat unter dem Kalender auswählen. 
```

2023-02-24 12:33 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +Klicken Sie nun auf {%button icon="download", lable ="Export starten"%} werden Ihnen die Arbeitszeitnachweise zum **herunterladen bereitgestellt**. Sollten Sie mehrere Mitarbeiter ausgewählt haben, f
```suggestion
Klicken Sie nun auf {% button icon="download", lable ="Export starten" %} werden Ihnen die Arbeitszeitnachweise zum **herunterladen bereitgestellt**. Sollten Sie mehrere Mitarbeiter ausgewählt haben, finden Sie diese als einzelne Dokumente in einem Ordner. 
```

2023-02-24 12:33 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +Im Datenexportmenü können Sie auch eine übersichtliche Kopie der Stammdaten ihrer Mitarbeiter anfordern. Klicken Sie dazu auf {%button label="Datenblatt"%} und wählen wieder die Abteilungen oder einz
```suggestion
Im Datenexportmenü können Sie auch eine übersichtliche Kopie der Stammdaten ihrer Mitarbeiter anfordern. Klicken Sie dazu auf {% button label="Datenblatt" %} und wählen wieder die Abteilungen oder einzelnen Mitarbeiter deren Daten Sie exportieren möchten. Auch hier haben Sie wieder die Möglichkeit das **Datenblatt direkt an eine Email Adresse zu verschicken**. Geben Sie dazu die Empfängeradresse in das Textfeld unter **Versenden an** ein. Mit einem Klick auf {% button label="**Export starten**" %} stehen Ihnen die Daten dann wieder zum Download bereit. 
```

2023-02-25 14:07 UTC, J0hhny commented
Änderungen integriert - Ticket für mehrere Mail Adressen beim Export steht noch offen. 
Sonst nur noch einmal Korrekturlesen

2023-03-08 14:18 UTC, MaKleSoft requested changes
Gute Arbeit! Bitte noch die angesprochenen Änderungen vornehmen - aber sonst top!

2023-03-08 14:18 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +> Wir empfehlen monatliche Lohnberichte stets durch Anwählen des Buttons [**Im Dokumentenarchiv ablegen**](#im-dokumentenarchiv-ablegen) in Pentacode zu hinterlegen. Zwar können Sie auch jederzeit Lo
Link funktioniert nicht. Wahrscheinlich wolltest du für die Option "Im Dokumentenarchiv ablegen" einen eigenen Abschnitt machen, hast das dann aber vergessen.

2023-03-08 14:18 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +**Im Dokumentenarchiv ablegen** sichert eine Kopie des Arbeitszeitennachweises im Dokumentenarchiv des Mitarbeiters und gewährt diesem auch Zugriff darauf. So, dass mit dem Anwählen von **Unterschrif
Wie gesagt, hierfür bitte einen eigenen Abschnitt, da Formatübergreifend. Bei der Gelegenheit kannst du auch gleich die Kategorien mit reinnehmen.

2023-03-08 14:18 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +- Generisch (Alle Kasssenbucheinträge als standardmäßige CSV-Datei für den Import in verschiedene Programme)
```suggestion
- Generisch (Alle Kassenbucheinträge als generische CSV-Datei für den Import in verschiedene Programme)
```

2023-03-08 14:18 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +> Wir empfehlen Ihnen ihre Mitarbeiter stets dazu aufzufordern den Arbeitszeitennachweis mit einer Unterschrift zu bestätigen - dies gibt Ihnen Sicherheit im Falle einer Prüfung und deckt Missverstän
Kleine Korrektur: Die Berechtigung "Dokumentenarchiv" in der MA-App ist **nicht** erforderlich. Solange der MA einen Zugang zur App hat, kann er auch Formale ausfüllen und unterschreiben. Zugriff zum Formular hat er direkt über die Startseite in der App.

2023-03-15 16:56 UTC, J0hhny commented
Einmal den ganzen Datenexport Artikel überarbeitet - hat jetzt eine neue Struktur, die übersichtlicher ist und die Inhalte wiederholen sich weniger. 

Einzig steht immer noch die Frage aus, ob es eine Funktion gibt die Exportdaten an mehrere Emails gleichzeitig zu verschicken. Sonst mergebereit

2023-03-20 09:23 UTC, MaKleSoft commented
> Einmal den ganzen Datenexport Artikel überarbeitet - hat jetzt eine neue Struktur, die übersichtlicher ist und die Inhalte wiederholen sich weniger.

Die neue Struktur gefällt mir sehr gut, allerdings hast du glaube ich die Überschriften-Levels durcheinandergebracht. "Lohnbuchhaltung" sollte z.b. eine `h3` Überschrift sein, da ja ein Unterpunkt von "Exportformat".

> Einzig steht immer noch die Frage aus, ob es eine Funktion gibt die Exportdaten an mehrere Emails gleichzeitig zu verschicken.

Geht aktuell noch nicht.

> Sonst mergebereit

Für die Zukunft: "Mergebereit" heißt es kann so **unverändert** gemerged werden. Das heißt solange noch irgendwelche Platzhalter oder Marker im Artikel sind, ist der PR nicht mergebereit. Ist mir vor allem deshalb wichtig, weil ich solche Sachen in Zukunft nicht mehr explizit prüfen werde und mehr und mehr deine Sorgfalt vertraue. Das heißt wenn du sagst "mergebereit", dann erwarte ich, dass ich den Merge-Button bedenkenlos drücken kann 😉

2023-03-20 09:28 UTC, MaKleSoft requested changes
Bis auf Überschriften-Level und Button Styling im letzten Abschnitt top!

2023-03-20 09:28 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +## Lohnbuchhaltung
```suggestion
### Lohnbuchhaltung
```

2023-03-20 09:28 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +## Arbeitszeitennachweis
```suggestion
### Arbeitszeitennachweis
```

2023-03-20 09:28 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +## Stammdatenblatt
```suggestion
### Stammdatenblatt
```

2023-03-20 09:28 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +## Kassenbuch
```suggestion
### Kassenbuch
```

2023-03-20 09:28 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +## Zeitraum
```suggestion
### Zeitraum
```

2023-03-20 09:28 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +## Mitarbeiterfilter
```suggestion
### Mitarbeiterfilter
```

2023-03-20 09:28 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +## Per Email versenden
```suggestion
### Per Email versenden
```

2023-03-20 09:28 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +## Im Dokumentenarchiv ablegen
```suggestion
### Im Dokumentenarchiv ablegen
```

2023-03-20 09:28 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +### Kategorie auswählen
```suggestion
#### Kategorie auswählen
```

2023-03-20 09:28 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +### Unterschrift anfordern
```suggestion
#### Unterschrift anfordern
```

2023-03-20 09:28 UTC, MaKleSoft commented on hilfe/handbuch/datenexport/index.md
> +- {% icon "eye" %} *Öffnen* Hier wird eine Vorschau der Datei in ihrem Browser oder in Excel geöffnet.
```suggestion
- {% button icon="eye" label="Öffnen" %} Hier wird eine Vorschau der Datei in ihrem Browser oder in Excel geöffnet.
```
Weiter unten das gleiche.

2023-03-28 11:35 UTC, MaKleSoft approved these changes

2023-03-28 11:35 UTC, merged