Einstellungen>Sonderleistungen
pentacode/site pull request #74
Opened 2023-02-13 20:05 UTC by J0hhny

Beschreibung wie die neuen Sonderleistungen funktionieren.

Noch zwei Punkte, die mir aufgefallen sind:
- Würde es nicht sinn machen zwischen jährlichen und Monatlichen Sonderleistungen zu unterscheiden z.B für Weihnachtsgeld, 13. Monatsgehalt
- Wo könnte man eine einmalige Zusatzzahlung zum Lohn hinzufügen? So etwas wie eine Prämie - mir scheint nämlich bis jetzt nur diese Option unter "Vorschüssen" zu bestehen.

2023-02-14 16:13 UTC, MaKleSoft commented
Kompiliert nicht, also da muss irgendwo noch ein Syntaxfehler sein. Bitte beheben!

> Noch zwei Punkte, die mir aufgefallen sind:
> 
> Würde es nicht sinn machen zwischen jährlichen und Monatlichen Sonderleistungen zu unterscheiden z.B für Weihnachtsgeld, 13. Monatsgehalt
> Wo könnte man eine einmalige Zusatzzahlung zum Lohn hinzufügen? So etwas wie eine Prämie - mir scheint nämlich bis jetzt nur diese Option unter "Vorschüssen" zu bestehen.

Hast du ganz richtig erfasst! Das wird vermutlich mit einem der nächsten Updates kommen.

2023-02-16 11:32 UTC, J0hhny commented
Kompilierungsfehler behoben.

2023-02-16 13:35 UTC, MaKleSoft requested changes

2023-02-16 13:35 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/sonderleistungen/index.md
> +- * Beitragsfrei -* Soll die Zusatzleistungen beitragsfrei angerechnet werden wie etwa SFN-Zuschläge? Wenn ja wählen Sie diese Option an, dass der Slider blau erscheint.
```suggestion
- *Beitragsfrei -* Soll die Zusatzleistungen beitragsfrei angerechnet werden wie etwa SFN-Zuschläge? Wenn ja wählen Sie diese Option an, dass der Slider blau erscheint.
```

2023-02-16 13:35 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/sonderleistungen/index.md
> +Um die Sonderleistung zu bearbeiten klicken Sie auf {%icon "ellipsis-h"%} neben der Sonderleistung. Wählen Sie **Bearbeiten** aus kommen Sie wieder in den gleichen Bearbeitungsdialog wie beim Erstell
Mach dir doch bitte die Mühe, wo möglich immer den Button-Style zu verwenden (also auch bei Menüpunkten). Das sieht schöner aus und hilft dem Nutzer, die entsprechende Funktion noch einfacher zu finden.

```suggestion
Um die Sonderleistung zu bearbeiten klicken Sie auf {% button icon="ellipsis-h" %} neben der Sonderleistung. Wählen Sie {% button label="Bearbeiten" icon="pencil" %}** aus kommen Sie wieder in den gleichen Bearbeitungsdialog wie beim Erstellen einer neuen Sonderleistung. Wählen Sie **Löschen** aus um die Sonderleistung zu löschen.
```

2023-02-16 13:35 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/sonderleistungen/index.md
> +Sonderleistungen sind eine Möglichkeit einer Gruppe an Mitarbeitern gesondert vom normalen Lohn zusätzliche Zahlungen zukommen zu lassen. Unter **Einstellungen>Sonderleistungen** können Sie Kategorie
Nachdem wir jetzt ja auch für die Untermenüs icons haben, wäre es finde ich cool, wenn wir die auch in den Hilfeartikeln bei verweisen auf die entsprechenden Bereiche verwenden.

```suggestion
Sonderleistungen sind eine Möglichkeit einer Gruppe an Mitarbeitern gesondert vom normalen Lohn zusätzliche Zahlungen zukommen zu lassen. Unter {% button label="Einstellungen" icon="cog" %} / {% button label="Sonderleistungen" icon="hand-holding-box" %} können Sie Kategorien anlegen um die lohn - und steuerrechtlichen Eigenschaften der Zusatzzahlungen zu definieren. 
```

2023-02-16 13:35 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/sonderleistungen/index.md
> +{%figure caption = "Unter Vertrag können Sie die Sonderleistungen bestimmen, die der Mitarbeiter erhalten soll - bspw. Fahrkostenzuschüsse."%}
Achte hier bitte auf eine konsistente Formatierung: Leerzeichen nach und vor `{%` und `%}`, **kein** Leerzeichen um `=` herum.

```suggestion
{% figure caption="Unter Vertrag können Sie die Sonderleistungen bestimmen, die der Mitarbeiter erhalten soll - bspw. Fahrkostenzuschüsse." %}
```

2023-02-16 13:35 UTC, MaKleSoft commented on hilfe/handbuch/einstellungen/sonderleistungen/index.md
> +Um die Sonderleistungen Mitarbeitern zuzuteilen, wählen Sie unter dem Reiter **Mitarbeiter** den gewünschten Angestellten aus und navigieren dann zu den **Verträgen**. Wenn Sie einen neuen Vertrag er
Auch hier bitte wieder bei Verweis auf die Menüpunkte "Mitarbeiter" und "Verträge" am besten den Button-Stil inkl. Icon verwenden. Ist zwar etwas mehr Arbeit aber ich finde die lohnt sich :)

2023-02-16 16:26 UTC, J0hhny commented
Alles auf button stil umgestellt - sollte soweit mergebereit sein.

2023-02-17 14:20 UTC, MaKleSoft approved these changes
Top!

2023-02-17 14:20 UTC, merged