Newsletter 1
pentacode/site pull request #85
Opened 2023-06-27 12:31 UTC by J0hhny

Erstmal die minimalistische Grundversion - um sinnvoll die Grafiken einzufügen muss ich nochmal was ausprobieren.

Findest du das Format so passend? Dann übertrag ich erstmal die restlichen Newsletter auch

2023-06-27 14:25 UTC, MaKleSoft requested changes
Bis auf meine Kommentare & Anregungen passt das so 👍

2023-06-27 14:25 UTC, MaKleSoft commented on blog/Newsletter1_Neues_Zeiterfassung/index.md
Ordner bitte umbenennen in `neues_zum_gesetz_der_zeiterfassung`. Großbuchstaben bitte generell vermeiden.

2023-06-27 14:25 UTC, MaKleSoft commented on blog/Newsletter1_Neues_Zeiterfassung/Glühbirne_ML.webp
Auch bei Dateinahmen bitte Großbuchstaben und Umlaute vermeiden. Also am besten umbennen in `gluehbirne_ml.webp`.

2023-06-27 14:25 UTC, MaKleSoft commented on blog/Newsletter1_Neues_Zeiterfassung/index.md
> +# Das Gesetz zur Zeiterfassung – und seine möglichen Folgen
Keine `h1` in Artikeln. Der Titel wird automatisch als `h1` gerendered.

2023-06-27 14:25 UTC, MaKleSoft commented on blog/Newsletter1_Neues_Zeiterfassung/index.md
> +# Das Gesetz zur Zeiterfassung – und seine möglichen Folgen
```suggestion
```

2023-06-27 14:25 UTC, MaKleSoft commented on blog/Newsletter1_Neues_Zeiterfassung/index.md
> +Dem Entwurf zufolge müssen Arbeitnehmer:innen Beginn, Ende und Dauer der Arbeit und damit auch Pausen und Unterbrechungen dokumentieren. Und zwar täglich und in elektronischer Form. Diese Form kann v
War das auch so im Newsletter? Ich dachte eigentlich, wir hätte mal entschieden, dass wir das mit dem "Gendern" komplett sein lassen. Klär das bitte mal mit dem Lorenz ab und pass es gegebenenfalls an.

```suggestion
Dem Entwurf zufolge müssen Arbeitnehmer Beginn, Ende und Dauer der Arbeit und damit auch Pausen und Unterbrechungen dokumentieren. Und zwar täglich und in elektronischer Form. Diese Form kann von einer einfachen Excel-Tabelle über eine Stechuhr bis zu einem Computerprogramm oder einer Handy-App reichen.
```

2023-06-27 14:25 UTC, MaKleSoft commented on blog/Newsletter1_Neues_Zeiterfassung/index.md
> +<b>Die Erfassung kann auch durch einen Vorgesetzten erfolgen, doch wer immer dies auch macht – die Verantwortung trägt immer der Arbeitgeber!</b>
```suggestion
**Die Erfassung kann auch durch einen Vorgesetzten erfolgen, doch wer immer dies auch macht – die Verantwortung trägt immer der Arbeitgeber!**
```

2023-06-27 14:25 UTC, MaKleSoft commented on blog/Newsletter1_Neues_Zeiterfassung/index.md
> +> Unabhängig von der Gesetzeslage sind Sie grundsätzlich bereits seit dem Urteil des BAGs vom September 2022 zur elektronischen Erfassung der Arbeitszeiten verpflichtet!
```suggestion
> **{% icon "lightbulb" %} Wichtig zu wissen!** Unabhängig von der Gesetzeslage sind Sie grundsätzlich bereits seit dem Urteil des BAGs vom September 2022 zur elektronischen Erfassung der Arbeitszeiten verpflichtet!
```

2023-06-27 14:25 UTC, MaKleSoft commented on blog/Newsletter1_Neues_Zeiterfassung/Überstundenkarte_ML.png
- Zu wenig Platz an den Rändern
- Dateinahme kleingeschrieben und mit ohne Umlaut
- Transparenter Hintergrund macht hier keinen Sinn. Bitte weißen Hintergrund nehmen.
- Umwandeln in `webp`.

2023-06-27 14:25 UTC, MaKleSoft commented on blog/Newsletter1_Neues_Zeiterfassung/index.md
> +{% endfigure %}
Probier doch mal, das Bild links oder rechts auszurichten, so dass der Text drum herum fließt. Siehe z.B. https://github.com/pentacode/site/blob/master/blog/zeiterfassung_wird_zur_pflicht/index.md?plain=1#L83-L86C10

```suggestion
<figure class="float left">
  <img src="Überstundenkarte_ML.png" alt="Infografik: Durchschnittliche Anzahl der wöchenlichen Überstunden nach Bundesland" />
  <figcaption>Deutsche Angestellte machten im Jahr 2021 insgesamt 1,7 Milliarden Überstunden (Laut einer Statistik, des Instituts für Arbeitsmarkt- und Berufsforschung)</figcaption>
</figure>
```

Die Syntax für die Abbildung ist übrigens auch ok bzw. sogar bevorzugt. Falls du dazu fragen hast sag bescheid.

2023-06-27 14:25 UTC, MaKleSoft commented on blog/Newsletter1_Neues_Zeiterfassung/Überstundenkarte_ML.png
Kannst hier eigentlich direkt das Bild vom "Zeiterfassung wird zur Pflicht" Artikel wiederverwenden.

2023-06-27 14:25 UTC, MaKleSoft commented on blog/Newsletter1_Neues_Zeiterfassung/index.md
> +*Ihr Pentacode-Team*
Ist keine Email, deshalb auch keine Grußworte nötig ;)

```suggestion
```

2023-06-27 15:05 UTC, MaKleSoft commented on blog/Newsletter1_Neues_Zeiterfassung/index.md
> +Dem Entwurf zufolge müssen Arbeitnehmer:innen Beginn, Ende und Dauer der Arbeit und damit auch Pausen und Unterbrechungen dokumentieren. Und zwar täglich und in elektronischer Form. Diese Form kann v
Ok, grade mit Lorenz gesprochen. Wir gendern nicht. Also das ":innen" bitte überall entfernen.

2023-06-28 11:34 UTC, J0hhny commented on blog/Newsletter1_Neues_Zeiterfassung/Überstundenkarte_ML.png
Hätte hier eigentlich doch das Bild aus dem Newsletter genutzt - sieht finde ich passender und weniger nach Stock-photo aus.

2023-06-28 11:36 UTC, J0hhny commented
Alles verbessert und soweit mergebereit.
Einzig fällt mir noch auf, dass vielleicht ein weiterer Reiter an Artikeln (Statt Ratgeber) für unsere Newsletter sinnvoll sein könnte, oder?

2023-06-29 13:21 UTC, MaKleSoft requested changes
Noch nicht ganz mergebereit. Siehe Kommentare.

2023-06-29 13:21 UTC, MaKleSoft commented on blog/newsletter1_neues_zum_gesetz_der_zeiterfassung/index.md
Das "newsletter1" bitte noch wegnehmen.

2023-06-29 13:21 UTC, MaKleSoft commented on blog/newsletter1_neues_zum_gesetz_der_zeiterfassung/index.md
> +cover: Zeiterfassung_ML.webp
```suggestion
cover: zeiterfassung_ml.webp
```

2023-06-29 13:21 UTC, MaKleSoft commented on blog/newsletter1_neues_zum_gesetz_der_zeiterfassung/ueberstundenkarte_ml.webp
Hier fehlt immer noch white space am Rand. So sieht es aktuell blöd aus (bitte auch immer die Preview anschauen und auf solche Sachen achten).

2023-06-29 13:23 UTC, MaKleSoft commented
> Einzig fällt mir noch auf, dass vielleicht ein weiterer Reiter an Artikeln (Statt Ratgeber) für unsere Newsletter sinnvoll sein könnte, oder?

Nein, der Newsletter ist keine eigene Kategorie, sondern eigentlich eine Sammlung an aktuellen Blogartikeln (aus allen Kategorien). Dieses mal haben wir ausnahmsweise die Emails zuerst geschrieben, aber normalerweise läuft es anders rum. Makes sense?

2023-06-29 13:31 UTC, MaKleSoft commented
@J0hhny Hab mir grade überlegt, dass dieser Artikel vermutlich besser in die Kategorie "Aktuelles" passt, da er ja eher zur Information dient. Der zweite Newletter-Artikel passt dann super in die Kategorie "Ratgeber".

2023-06-29 13:31 UTC, MaKleSoft commented on blog/newsletter1_neues_zum_gesetz_der_zeiterfassung/index.md
> +    - ratgeber
```suggestion
    - aktuelles
```

2023-07-03 12:39 UTC, J0hhny commented on blog/newsletter1_neues_zum_gesetz_der_zeiterfassung/ueberstundenkarte_ml.webp
Beziehst du dich hier auf die Umbrüche in den Wörtern? Also, dass die Schrift mehr im Blockstil steht?

2023-07-17 09:07 UTC, MaKleSoft commented
Bei dem einen Bild fehlt immer noch das "padding" am Rand. Außerdem bitte die Kategorie noch in "Aktuelles" abändern.


<img width="664" alt="Screenshot 2023-07-17 at 11 05 10" src="https://github.com/pentacode/site/assets/1270940/183b84d4-c1f3-4720-82b1-841abfb42517">

2023-07-18 19:53 UTC, J0hhny commented
Habe jetzt sowohl dem Bild mehr Rand hinzugefügt (sieht so auch deutlich besser aus) als auch leichtes Padding mit whitespace - dies ist aber bei unsere restlichen Blogartikeln nicht die Norm (falls es nur um den Rand ging, gerne auch entfernen)

2023-07-19 06:51 UTC, MaKleSoft approved these changes

2023-07-19 06:51 UTC, merged