Newsletter3
pentacode/site pull request #87
Opened 2023-07-07 15:29 UTC by J0hhny

nur für mich noch nicht fertig!

2023-07-17 09:34 UTC, MaKleSoft requested changes

2023-07-17 09:34 UTC, MaKleSoft commented on blog/zeiterfassung_ueberstunden_vermeiden/index.md
> +cover: zeiterfassungssysteme_header.webp
Bild fehlt.

2023-07-17 09:34 UTC, MaKleSoft commented on blog/zeiterfassung_ueberstunden_vermeiden/index.md
> +--
Fehlt hier noch was? Falls nicht bitte entfernen.

2023-07-17 09:34 UTC, MaKleSoft commented on blog/zeiterfassung_ueberstunden_vermeiden/index.md
> +--
Hier wäre ein Screenshot der Drag & Drop-Funktion ganz cool, oder?

2023-07-17 09:34 UTC, MaKleSoft commented on blog/zeiterfassung_ueberstunden_vermeiden/index.md
> +**Dasselbe gilt für ein Zuspätkommen.**
Ich glaube hier braucht es ein bisschen mehr Erklärung.

2023-07-18 19:59 UTC, J0hhny commented on blog/zeiterfassung_ueberstunden_vermeiden/index.md
> +--
Da scheint mir etwas falsch gelaufen zu sein beim Upload - sowohl Cover als auch das gif. der Drag & Drop ist vorhanden

2023-07-18 22:46 UTC, J0hhny commented
Das .gif muss ich noch durch ein besser auflösendes ersetzen

2023-07-19 06:56 UTC, MaKleSoft commented
> Das .gif muss ich noch durch ein besser auflösendes ersetzen

Japp, und bitte im 4:3 oder wenigstens 3:2 format. Also nicht so länglich. Denk drank, dass es auch auf mobile einigermaßen gut aussehen muss.

2023-07-22 15:51 UTC, J0hhny commented
jetzt fertig

2023-07-23 11:23 UTC, J0hhny commented
Ist jetzt das neue Gif richtig drinnen?

2023-07-23 11:54 UTC, MaKleSoft approved these changes

2023-07-23 11:54 UTC, merged