Newsletter4
pentacode/site pull request #88
Opened 2023-07-07 20:31 UTC by J0hhny

2023-07-07 20:36 UTC, J0hhny commented
Mir ist aufgefallen, dass die Blockartikel nicht so schön im Blockformat sind wie einige andere Artikel (siehe z.B die Erfahrungsberichte) - weißt du welche Einstellung mir das fehlt? Bei VS Code ist die Zeilenlänge fix auf 80 beschränkt

2023-07-18 22:44 UTC, J0hhny commented
Dieser Newsletter hätte jetzt gerade Priorität, da ich auf ihn in der nächsten Mailkampagne verlinken will.

2023-07-19 06:57 UTC, MaKleSoft commented
> Mir ist aufgefallen, dass die Blockartikel nicht so schön im Blockformat sind wie einige andere Artikel (siehe z.B die Erfahrungsberichte) - weißt du welche Einstellung mir das fehlt? Bei VS Code ist die Zeilenlänge fix auf 80 beschränkt

Weiß nicht, worauf du dich genau beziehst. Was meinst du mit "Blockformat"?

2023-07-19 07:18 UTC, MaKleSoft requested changes
Bis auf den falschen Titel und "fehlende" Einleitung bereit zum mergen!

2023-07-19 07:18 UTC, MaKleSoft commented on blog/zeiterfassung_dienstplanung/index.md
> +title: Zeiterfassung - Möglichkeiten, Risiken & Nebenwirkungen
Falscher Titel?

2023-07-19 07:18 UTC, MaKleSoft commented on blog/zeiterfassung_dienstplanung/index.md
> +
Ich weiß, der Artikel ist größtenteils aus dem Booklet entnommen und vermutlich bereits durch Lorenz abgesegnet, aber mir fehlt hier noch eine kurze Einleitung. Was ist das Thema, was die Motivation? Aktuell fühlt es sich so an, also würde ich in der Mitte anfangen zu lesen 😅

2023-07-19 07:18 UTC, MaKleSoft commented on blog/zeiterfassung_dienstplanung/index.md
> +
Vorschlag von ChatGPT: 

> Effizienz und strategische Planung sind entscheidend für den Erfolg eines Unternehmens. In diesem Artikel untersuchen wir zwei leistungsstarke Werkzeuge zur Optimierung der betrieblichen Abläufe und zur Reduzierung von Personalkosten. Wir konzentrieren uns dabei auf das Management von "Leerlaufzeiten" und die Bedeutung von Daten in der Personalplanung. Lesen Sie weiter und erfahren Sie, wie Sie mit diesen Methoden Ihre Unternehmensleistung steigern können.

2023-07-19 07:24 UTC, MaKleSoft requested changes
Ein Fehler beim Datum ist mir noch aufgefallen.

2023-07-19 07:24 UTC, MaKleSoft commented on blog/zeiterfassung_dienstplanung/index.md
> +date: 2023-27-06
Format ist immer `YYYY-MM-DD`.

```suggestion
date: 2023-06-27
```

2023-07-22 12:12 UTC, J0hhny commented
Mit der Einleitung hast du Recht - wenn man die ganze Zeit die Artikel quer liest wird man relativ betriebsblind.

Ist jetzt soweit fertig.

2023-07-22 13:21 UTC, MaKleSoft approved these changes

2023-07-22 13:21 UTC, merged