Newsletter 6
pentacode/site pull request #91
Opened 2023-08-21 14:16 UTC by J0hhny

Erste Vorlage zum Newsletter 6 - find ich inhaltlich etwas schwer verständlich aber geht glaube ich kaum anders.

2023-08-22 08:18 UTC, MaKleSoft requested changes
Sieht gut aus! Nur ein paar Kleinigkeiten:

- Bitte Titel anpassen so dass er konsistent ist mit dem Vorgängerartikel
- Bitte keine Leerzeichen in Datei- oder Ordnernamen. Denk außerdem dran, dass der Ordnername am Ende auch die URL bestimmt. Aktuell ist dir URL `/blog/dienstplanung%202.0/` was natürlich nicht so schön ist. Also bitte den Ordner in `dienstplanung_2` umbenennen (das `.0` hat hier nichts zu suchen, ist ja keine Software version).
- Die Bilder haben eine sehr niedrige Auflösung. Hast du die so geliefert bekommen? Wäre schon gut die in einer besseren Qualität zu haben.

2023-08-22 08:18 UTC, MaKleSoft commented on blog/dienstplanung 2.0/index.md
> +title: Ihr Dienstplan - Malen nach Zahlen, Teil 2
```suggestion
title: Dienstplanung Teil 2 - Malen nach Zahlen
```

2023-08-27 18:20 UTC, J0hhny commented
Titel angepasst - die Bilder habe ich leider so bekommen, in kleinerem Format finde ich, dass sie etwas besser aussehen

2023-08-28 08:01 UTC, MaKleSoft approved these changes

2023-09-01 10:23 UTC, merged