Newsletter7
pentacode/site pull request #93
Opened 2023-08-24 11:34 UTC by J0hhny

2023-08-24 11:38 UTC, J0hhny commented
Das Bild ist nicht unbedingt nötig - dachte aber das macht es etwas ansprechender und gibt eine weitere Chance zur Verlinkung

2023-09-01 11:05 UTC, J0hhny commented
@MaKleSoft soweit fertig

2023-09-13 09:48 UTC, MaKleSoft requested changes
Bitte für Fußnote die entsprechende Syntax verwenden. Siehe: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes

2023-09-13 09:48 UTC, MaKleSoft commented on blog/lohnkosten_im_vergleich/index.md
> +Gesamtwirtschaftlich liegen die Lohnkosten in Deutschland mit 27 € pro Stunde nur 5 € über dem Durchschnitt des Euroraumes. In diesen Euroraum-Durchschnitt fließt aber mehr als die Hälfte aller Staat
Für Fußnoten gibt es in Markdown eine spezielle Syntax:

```suggestion
Gesamtwirtschaftlich liegen die Lohnkosten in Deutschland mit 27 € pro Stunde nur 5 € über dem Durchschnitt des Euroraumes. In diesen Euroraum-Durchschnitt fließt aber mehr als die Hälfte aller Staaten ein, bei denen die Lohnkosten pro Stunde zwischen 20 € (Slowenien) und 4 € (Bulgarien) liegen. Im Vergleich zu den europäischen „Kernstaaten“ liegt Deutschland im unteren Drittel. Nur Schweden, Frankreich, Österreich und Italien haben einen geringeren Lohndurchschnitt [^1].
```

2023-09-13 09:48 UTC, MaKleSoft commented on blog/lohnkosten_im_vergleich/index.md
> +Auch bei den oft beklagten Lohnnebenkosten sind die Annahmen der meisten falsch. Im EU-Vergleich der Lohnnebenkosten (Arbeitgeber) führt Deutschland mit 27 € Lohnnebenkosten je 100 € Lohn nur die unt
```suggestion
Auch bei den oft beklagten Lohnnebenkosten sind die Annahmen der meisten falsch. Im EU-Vergleich der Lohnnebenkosten (Arbeitgeber) führt Deutschland mit 27 € Lohnnebenkosten je 100 € Lohn nur die untere Hälfte an. Österreich wartet, nur zum Vergleich, mit 39 € auf, der Schnitt der EU-19 liegt bei 34 € [^2].
```

2023-09-13 09:48 UTC, MaKleSoft commented on blog/lohnkosten_im_vergleich/index.md
> +Ganz ähnlich sieht es bei der Betrachtung des Mindestlohns aus. Im Sinne der Armutsvermeidung gilt ein Mindestlohn erst dann als angemessen, wenn er 60% des Durchschnittslohns erreicht. Bis zum 1. Ok
```suggestion
Ganz ähnlich sieht es bei der Betrachtung des Mindestlohns aus. Im Sinne der Armutsvermeidung gilt ein Mindestlohn erst dann als angemessen, wenn er 60% des Durchschnittslohns erreicht. Bis zum 1. Oktober 2022 lag der relative Wert des Mindestlohns in Deutschland jedoch nur bei 45,6%. Innerhalb Europas schnitten bisher nur Estland, Tschechien und Spanien noch schlechter ab [^3].
```

2023-09-13 09:48 UTC, MaKleSoft commented on blog/lohnkosten_im_vergleich/index.md
> +<p style="font-size: 80%;">(1) Eurostat, 11. April 2019 </p>
```suggestion
[^1]: Eurostat, 11. April 2019
```

2023-09-13 09:48 UTC, MaKleSoft commented on blog/lohnkosten_im_vergleich/index.md
> +<p style="font-size: 80%;">(2) Statistisches Bundesamt auf Basis von Eurostat, 23. April 2020 </p>
```suggestion
[^2]: Statistisches Bundesamt auf Basis von Eurostat, 23. April 2020
```

2023-09-13 09:48 UTC, MaKleSoft commented on blog/lohnkosten_im_vergleich/index.md
> +<p style="font-size: 80%;">(3) WSI-Mindestlohndatenbank 2020 </p>
```suggestion
[^3]: WSI-Mindestlohndatenbank 2020
```

2023-09-22 11:25 UTC, J0hhny commented
@MaKleSoft Fußzeilen angepasst - kann den letzten Change request aber nicht abhaken.

2023-09-22 11:30 UTC, J0hhny commented
Hier merke ich nur, wenn ich auf die Verweise auf die Referenzen klicke, springe ich zu weit runter auf die Seite - bin aber wirklich überfragt, was hier da Problem ist.

2023-09-22 14:53 UTC, MaKleSoft approved these changes
> Hier merke ich nur, wenn ich auf die Verweise auf die Referenzen klicke, springe ich zu weit runter auf die Seite - bin aber wirklich überfragt, was hier da Problem ist.

Das passt schon so.

2023-09-23 11:16 UTC, merged