Newsletter9
pentacode/site pull request #95
Opened 2023-08-26 19:29 UTC by J0hhny

Veröffentlichung erst zum 28.8

2023-08-28 08:07 UTC, MaKleSoft requested changes
Ich denke den Titel musst du noch ändern.

2023-08-28 08:07 UTC, MaKleSoft commented on blog/pauschale_vorrauszahlungen/index.md
> +title: SFN-Zuschläge strategisch nutzen
Gleicher Titel wie der Vorgängerartikel?

2023-08-28 08:07 UTC, MaKleSoft commented on blog/pauschale_vorrauszahlungen/index.md
> +desNetto-Auszahlungsbetrags an den Mitarbeiter.
```suggestion
des Netto-Auszahlungsbetrags an den Mitarbeiter.
```

2023-09-01 11:25 UTC, J0hhny commented
Da die beiden Newsletter thematisch stark zusammen hängen, habe ich diesen jetzt mal mit Teil2 benannt

2023-09-13 09:50 UTC, MaKleSoft approved these changes

2023-09-13 09:51 UTC, merged