newsletter 10
pentacode/site pull request #96
Opened 2023-08-27 19:41 UTC by J0hhny

2023-08-28 08:24 UTC, MaKleSoft requested changes

2023-08-28 08:24 UTC, MaKleSoft commented on blog/hinweise_zuschläge/index.md
> +title: Bei Zuschlagszahlungen zu beachten
Ich glaube, da finden wir einen besseren Titel... Darf ruhig ein bisschen Klickbaity sein. Zum Beispiel:

"4 essentielle Tips für das Arbeiten mit Zuschlägen"

2023-08-28 08:24 UTC, MaKleSoft commented on blog/hinweise_zuschläge/index.md
> +## TIPP 1
```suggestion
## Tipp #1: Vorsicht bei Vertragsänderungen!
```

2023-08-28 08:24 UTC, MaKleSoft commented on blog/hinweise_zuschläge/index.md
> +## TIPP 2
```suggestion
## Tipp #2: Nutzen Sie Zuschläge in Gehaltsverhandlungen
```

2023-08-28 08:24 UTC, MaKleSoft commented on blog/hinweise_zuschläge/index.md
> +Sie können Zuschlagszahlungen in der Höhe begrenzen.
```suggestion
## Tipp #3: Sie können Zuschlagszahlungen in der Höhe begrenzen.
```

2023-08-28 08:24 UTC, MaKleSoft commented on blog/hinweise_zuschläge/index.md
> +## TIPP 4
```suggestion
## Tipp #4: Vermeiden Sie Überbezahlung durch SFN-Pauschalen
```

2023-09-01 11:26 UTC, J0hhny commented on blog/hinweise_zuschläge/index.md
> +title: Bei Zuschlagszahlungen zu beachten
Ist noch ein Arbeitstitel, da ich von Lorenz bisher nichts bekommen habe für die Kampagne

2023-09-03 01:02 UTC, J0hhny commented
Titel angepasst - jetzt fertig

2023-09-06 11:24 UTC, MaKleSoft commented
> Titel angepasst - jetzt fertig
Hm, so richtig gefällt mir der Titel immer noch nicht, da auch nicht wirklich "catchy". Hat der Lorenz dir den vorgegeben?

2023-09-06 11:50 UTC, MaKleSoft requested changes
Bitte noch Titel und Ordner/URL ändern.

2023-09-06 11:50 UTC, MaKleSoft commented on blog/hinweise_zuschläge/index.md
> +title: Finale Tipps zu SFN-Zuschlägen
Bitte wie folgt ändern:
```suggestion
title: 4 essentielle Tipps für das Arbeiten mit Zuschlägen
```

2023-09-06 11:50 UTC, MaKleSoft commented on blog/hinweise_zuschläge/index.md
Ordner bitte umbenennen in `4_tipps_zuschlaege`.

2023-09-12 14:11 UTC, MaKleSoft requested changes
Ordner ist leider immer noch nicht umbenannt... Bitte umbenennen in `4_tipps_zuschlaege`.

2023-09-13 09:14 UTC, J0hhny commented
Alle Newsletter sollten jetzt fertig für den Blog sein - habe alle Änderungen integriert und der 11 muss noch einmal redigiert werden.

2023-09-13 09:39 UTC, MaKleSoft approved these changes

2023-09-13 09:40 UTC, merged