Newsletter11
pentacode/site pull request #97
Opened 2023-09-13 09:11 UTC by J0hhny

2023-09-14 07:12 UTC, MaKleSoft requested changes

2023-09-14 07:12 UTC, MaKleSoft commented on blog/wort_zum_abschied/index.md
> +Die Arbeits- und Motivationspsychologie hat umfassend erfosrscht, was Menschen zu guter Leistung motiviert, unter welchen Umständen das Versprechen von mehr Geld demotivierend ist, warum Mitarbeiter,
```suggestion
Die Arbeits- und Motivationspsychologie hat umfassend erforscht, was Menschen zu guter Leistung motiviert, unter welchen Umständen das Versprechen von mehr Geld demotivierend ist, warum Mitarbeiter, die für die gleiche Tätigkeit weniger Geld erhalten als die Kollegen, oft trotzdem motivierter sind als die besser Bezahlten und vieles mehr.
```

2023-09-14 07:12 UTC, MaKleSoft commented on blog/wort_zum_abschied/index.md
> +title: Ein Wort zum Abschied
Also bei der Titelwahl hätte ich mir wirklich gewünscht, dass du dir mehr Gedanken machst und nicht einfach blind die Titel aus dem Buch übernimmst (ich nehme an, das ist, was hier passiert ist). Blogartikel, auch wenn sie Teil einer Reihe sind, müssten immer auch für sich alleine stehen können und ein Titel muss aussagekräftig genug sein, dass der Leser zumindest eine Idee hat, worum es geht ohne den Kontext zu kennen.

Stell dir vor du besuchst die Seite zum ersten mal und klickst auf "Blog", und dann ist der erste Artikel in der Liste "Ein Wort zum Abschied". Was glaubst du ist der erste Gedanke?

<img width="1287" alt="Screenshot 2023-09-14 at 09 08 44" src="https://github.com/pentacode/site/assets/1270940/e8fefc0a-54fc-441b-828c-eaa338fca0a7">

2023-09-22 11:43 UTC, J0hhny commented
@MaKleSoft Auch hier sind die Änderungen angepasst - bitte noch einmal draufschauen ob es aus deiner Sicht passt.

2023-09-22 14:58 UTC, MaKleSoft approved these changes

2023-09-22 14:58 UTC, MaKleSoft commented on blog/lohnkosten_im_vergleich/index.md
Die Datei hat in dem PR nichts zu suchen. Vielleicht besser rausnehmen, bevor es zu Mergekonflikten kommt.

2023-09-22 14:58 UTC, MaKleSoft commented on blog/personalkosten_zum_unternehmenserfolg/index.md
> +title: Personalkosten - die Stellschraube zum Unternehmenserfolg
Geht doch 😉

2023-09-23 11:22 UTC, merged